// GENERATED FILE — DO NOT EDIT. Source: contracts/openapi/*.yaml

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457 Problem Details with stable machine-readable extensions.
         * @example {
         *       "type": "about:blank",
         *       "title": "Validation failed",
         *       "status": 400,
         *       "detail": "One or more fields are invalid.",
         *       "instance": "/v1/example",
         *       "code": "VALIDATION_ERROR",
         *       "requestId": "0190f7d2-8f9c-7abc-8def-0123456789ab"
         *     }
         */
        ProblemDetails: {
            /**
             * Format: uri-reference
             * @description A URI reference identifying the problem type.
             */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance: string;
            code: components["schemas"]["ErrorCode"];
            /** @description Correlation identifier assigned by the server. */
            requestId: string;
        };
        /**
         * Format: uuid
         * @description Server-generated UUID version 7 with RFC 9562 variant bits.
         * @example 0190f7d2-8f9c-7abc-8def-0123456789ab
         */
        UuidV7: string;
        /**
         * Format: date-time
         * @description ISO 8601 timestamp in UTC; serialized with a trailing Z.
         * @example 2026-09-08T00:00:00Z
         */
        Timestamp: string;
        /**
         * @example {
         *       "items": [],
         *       "nextCursor": null
         *     }
         */
        CursorPage: {
            items: unknown[];
            /** @description Opaque cursor for the next page, or null at the end. */
            nextCursor: string | null;
        };
        /**
         * @description Major URL version; incompatible changes require a new value.
         * @example v1
         * @enum {string}
         */
        ApiVersion: "v1";
        /**
         * @description Stable machine-readable error code. Add codes to x-error-codes first.
         * @example VALIDATION_ERROR
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "VERSION_CONFLICT" | "UNPROCESSABLE_ENTITY" | "UPSTREAM_UNAVAILABLE" | "INTERNAL_ERROR";
    };
    responses: {
        /** @description Request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication is required or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated caller is not allowed to perform this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist or is not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request conflicts with current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request is syntactically valid but semantically invalid. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unexpected server failure. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description A required service is temporarily unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        /** @description Strong entity-tag encoding the expected decimal resource version; mismatch produces VERSION_CONFLICT (409). */
        IfMatch: string;
        /** @description Unique key per logical mutation; retained for at least 24 hours. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
