import { Type } from 'class-transformer';
import { IsArray, IsIn, IsInt, IsObject, IsOptional, IsString, Matches, Max, MaxLength, Min, ValidateNested } from 'class-validator';

const roles = ['BATCH_MEDIA', 'INTERACTIVE_TTS'];
export class WorkerListQueryDto { @IsOptional() @IsString() cursor?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit?: number; @IsOptional() @IsString() role?: string; @IsOptional() @IsString() observedStatus?: string; @IsOptional() @IsString() desiredStatus?: string; @IsOptional() @IsString() provider?: string; @IsOptional() @IsString() @MaxLength(120) query?: string; }
export class CreateImageDto { @IsIn(roles) role!: 'BATCH_MEDIA' | 'INTERACTIVE_TTS'; @IsString() semanticVersion!: string; @IsString() imageDigest!: string; @IsString() registryRef!: string; @IsInt() @Min(1) contractVersion!: number; @IsArray() @IsString({ each: true }) capabilities!: string[]; }
export class CreateWorkerDto { @IsString() @MaxLength(120) displayName!: string; @IsIn(roles) role!: 'BATCH_MEDIA' | 'INTERACTIVE_TTS'; @IsString() @MaxLength(80) provider!: string; @IsOptional() @IsString() @MaxLength(160) providerInstanceId?: string; @IsOptional() @IsString() @MaxLength(160) expectedGpuModel?: string; @IsOptional() @IsInt() @Min(0) expectedVramMb?: number; @IsString() approvedImageId!: string; @IsString() hourlyRateCp!: string; @IsOptional() @IsString() paidVndPerCp?: string; @IsString() billingStartedAt!: string; }
export class WorkerCapacityDto { @IsInt() @Min(1) @Max(64) maxConcurrentTasks!: number; @IsInt() @Min(0) @Max(64) availableTaskSlots!: number; @IsString() @Matches(/^\d+$/u) scratchFreeBytes!: string; @IsOptional() @IsInt() @Min(0) vramFreeMb?: number; }
export class EnrollmentDto { @IsString() sessionNonce!: string; @IsIn(roles) role!: 'BATCH_MEDIA' | 'INTERACTIVE_TTS'; @IsString() imageDigest!: string; @IsString() agentVersion!: string; @IsInt() @Min(1) contractVersion!: number; @IsArray() @IsString({ each: true }) capabilities!: string[]; @IsArray() gpuInventory!: unknown[]; @IsObject() cpuInventory!: Record<string, unknown>; @ValidateNested() @Type(() => WorkerCapacityDto) capacity!: WorkerCapacityDto; }
export class HeartbeatDto { @IsString() sequence!: string; @IsString() sentAt!: string; @ValidateNested() @Type(() => WorkerCapacityDto) capacity!: WorkerCapacityDto; @IsInt() @Min(0) currentTaskCount!: number; @IsArray() @IsString({ each: true }) activeLeaseIds!: string[]; @IsObject() telemetry!: Record<string, unknown>; @IsString() agentVersion!: string; @IsInt() @Min(1) contractVersion!: number; }
