ALTER TABLE "assets" ADD COLUMN "duration_ms" INTEGER, ADD COLUMN "created_by_attempt_id" UUID, ADD COLUMN "delete_after" TIMESTAMPTZ(6), ADD COLUMN "deleted_at" TIMESTAMPTZ(6);
CREATE TYPE "VideoAssetKind" AS ENUM ('RAW','DESUBBED','OCR_JSON','ASR_JSON','TRANSCRIPT_JSON','BACKGROUND_AUDIO','VOCALS','DUB_AUDIO','PREVIEW','OUTPUT_VIDEO','OUTPUT_SUBTITLE','THUMBNAIL','LOG','OTHER');
CREATE TYPE "RenderOutputVariant" AS ENUM ('FULL_16X9','HIGHLIGHT_9X16','CUSTOM');
CREATE TYPE "RenderOutputStatus" AS ENUM ('DRAFT','READY','APPROVED','SUPERSEDED');
CREATE TABLE "video_assets" ("id" UUID NOT NULL,"video_id" UUID NOT NULL,"asset_id" UUID NOT NULL,"kind" "VideoAssetKind" NOT NULL,"variant_key" TEXT,"revision" INTEGER NOT NULL DEFAULT 1,"is_current" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "video_assets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "render_outputs" ("id" UUID NOT NULL,"video_id" UUID NOT NULL,"pipeline_job_id" UUID,"variant" "RenderOutputVariant" NOT NULL,"revision" INTEGER NOT NULL DEFAULT 1,"video_asset_id" UUID,"subtitle_asset_id" UUID,"thumbnail_asset_id" UUID,"status" "RenderOutputStatus" NOT NULL DEFAULT 'DRAFT',"approved_by" UUID,"approved_at" TIMESTAMPTZ(6),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "render_outputs_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "video_assets_video_id_kind_variant_key_revision_key" ON "video_assets"("video_id","kind","variant_key","revision");
CREATE INDEX "video_assets_video_id_kind_variant_key_is_current_idx" ON "video_assets"("video_id","kind","variant_key","is_current");
CREATE UNIQUE INDEX "video_assets_one_current_idx" ON "video_assets"("video_id","kind",COALESCE("variant_key",'')) WHERE "is_current" = true;
CREATE UNIQUE INDEX "render_outputs_video_id_variant_revision_key" ON "render_outputs"("video_id","variant","revision");
CREATE INDEX "render_outputs_video_id_variant_status_idx" ON "render_outputs"("video_id","variant","status");
CREATE UNIQUE INDEX "render_outputs_one_approved_idx" ON "render_outputs"("video_id","variant") WHERE "status" = 'APPROVED';
CREATE INDEX "assets_created_by_attempt_id_idx" ON "assets"("created_by_attempt_id");
ALTER TABLE "assets" ADD CONSTRAINT "assets_created_by_attempt_id_fkey" FOREIGN KEY ("created_by_attempt_id") REFERENCES "task_attempts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "video_assets" ADD CONSTRAINT "video_assets_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "videos"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "video_assets" ADD CONSTRAINT "video_assets_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "render_outputs" ADD CONSTRAINT "render_outputs_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "videos"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "render_outputs" ADD CONSTRAINT "render_outputs_pipeline_job_id_fkey" FOREIGN KEY ("pipeline_job_id") REFERENCES "pipeline_jobs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "render_outputs" ADD CONSTRAINT "render_outputs_video_asset_id_fkey" FOREIGN KEY ("video_asset_id") REFERENCES "video_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "render_outputs" ADD CONSTRAINT "render_outputs_subtitle_asset_id_fkey" FOREIGN KEY ("subtitle_asset_id") REFERENCES "video_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "render_outputs" ADD CONSTRAINT "render_outputs_thumbnail_asset_id_fkey" FOREIGN KEY ("thumbnail_asset_id") REFERENCES "video_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "render_outputs" ADD CONSTRAINT "render_outputs_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
