import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const contractDir = join(root, 'contracts/openapi');
const generatedRoot = process.env.CONTRACT_GENERATED_ROOT ?? root;
const outputDir = join(generatedRoot, 'packages/api-contract/src');
const schemaDir = join(generatedRoot, 'packages/api-contract/schemas');
const header = '// GENERATED FILE — DO NOT EDIT. Source: contracts/openapi/*.yaml\n\n';
const contracts = [
  { name: 'web', source: 'web.openapi.yaml' },
  { name: 'worker', source: 'worker.openapi.yaml' },
];
const documents = new Map();

mkdirSync(outputDir, { recursive: true });
rmSync(schemaDir, { recursive: true, force: true });
mkdirSync(schemaDir, { recursive: true });

for (const contract of contracts) {
  const source = join(contractDir, contract.source);
  const target = join(outputDir, `${contract.name}.ts`);
  execFileSync(
    'pnpm',
    [
      'exec',
      'openapi-typescript',
      source,
      '--output',
      target,
      '--redocly',
      join(contractDir, '.redocly.yaml'),
    ],
    { cwd: root, stdio: 'inherit' },
  );
  const contents = readFileSync(target, 'utf8').replace(
    /^\/\/ This file was auto-generated by openapi-typescript.*\n/m,
    '',
  );
  writeFileSync(target, header + contents, 'utf8');
  generateOperationSchemas(source, contract.name);
}

const operations = readdirSync(schemaDir)
  .filter((file) => file.endsWith('.json') && file !== 'index.json')
  .map((file) => file.slice(0, -5))
  .sort();
writeFileSync(
  join(schemaDir, 'index.json'),
  `${JSON.stringify(
    {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      title: 'Reup Dubbing Studio generated operation schemas',
      type: 'object',
      properties: { operations: { type: 'array', items: { type: 'string' } } },
      required: ['operations'],
      additionalProperties: false,
      operations,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

function generateOperationSchemas(source, contractName) {
  const document = YAML.parse(readFileSync(source, 'utf8'));
  documents.set(source, document);
  for (const [path, pathItem] of Object.entries(document.paths ?? {}).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    for (const [method, operation] of Object.entries(pathItem).sort(([a], [b]) =>
      a.localeCompare(b),
    )) {
      if (!['get', 'put', 'post', 'patch', 'delete', 'head', 'options', 'trace'].includes(method))
        continue;
      if (!operation.operationId)
        throw new Error(`${source}: ${method.toUpperCase()} ${path} is missing operationId`);
      const schema = {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        $id: `urn:reup-dubbing-studio:${contractName}:operation:${operation.operationId}`,
        title: operation.summary ?? operation.operationId,
        type: 'object',
        properties: {
          request: resolveSchema(
            operation.requestBody?.content?.['application/json']?.schema ?? {},
            source,
          ),
          responses: Object.fromEntries(
            Object.entries(operation.responses ?? {})
              .sort(([a], [b]) => a.localeCompare(b))
              .map(([status, response]) => [
                status,
                resolveSchema(response.content?.['application/json']?.schema ?? {}, source),
              ]),
          ),
        },
        required: ['request', 'responses'],
        additionalProperties: false,
      };
      writeFileSync(
        join(schemaDir, `${operation.operationId}.json`),
        `${JSON.stringify(schema, null, 2)}\n`,
        'utf8',
      );
    }
  }
}

function resolveSchema(value, source) {
  if (Array.isArray(value)) return value.map((item) => resolveSchema(item, source));
  if (!value || typeof value !== 'object') return value;
  if (typeof value.$ref === 'string') {
    const [targetFile, fragment] = value.$ref.split('#');
    const target = resolve(targetFile ? join(dirname(source), targetFile) : source);
    if (!documents.has(target)) documents.set(target, YAML.parse(readFileSync(target, 'utf8')));
    const pointer = (fragment ?? '')
      .split('/')
      .filter(Boolean)
      .map((part) => part.replaceAll('~1', '/').replaceAll('~0', '~'));
    let resolved = documents.get(target);
    for (const part of pointer) resolved = resolved?.[part];
    const expanded = resolveSchema(resolved ?? {}, target);
    const siblings = Object.fromEntries(Object.entries(value).filter(([key]) => key !== '$ref'));
    return { ...expanded, ...resolveSchema(siblings, source) };
  }
  return Object.fromEntries(
    Object.entries(value).map(([key, child]) => [key, resolveSchema(child, source)]),
  );
}
