import { createHash } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';
import type { StudioEnvelope, StudioReviewRequest, StudioSegmentPatch } from '@reup-dubbing-studio/api-contract';
import { uuidV7 } from '../../../platform/ids/uuid-v7';
import { StudioError } from '../domain/studio-errors';
import { resolveReviewPolicySnapshot } from '../../review-policy/infrastructure/prisma-review-policy-repository';
/* eslint-disable @typescript-eslint/no-explicit-any, @stylistic/brace-style */
const OWNER_ID = '01994429-ec00-7000-8000-000000000002';
const activeJobs = ['QUEUED','RUNNING','WAITING_FOR_GPU','WAITING_FOR_REVIEW'] as const;
export type SegmentPatch = StudioSegmentPatch;
export type ReviewInput = StudioReviewRequest;
export class PrismaStudioRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async detail(videoId: string) { const row = await this.prisma.video.findUnique({
    where: { id: videoId }, include: {
      sourceContent: true,
      seriesProfile: { include: { castSheet: { include: { entries: { include: { voiceProfile: true } } } } } },
      segments: { orderBy: { ordinal: 'asc' }, include: { currentRevision: { include: { voiceProfile: true, castSheetEntry: true, audioRevisions: { orderBy: { revision: 'desc' }, include: { asset: true } } } } } },
      transcriptRuns: { orderBy: { createdAt: 'desc' } },
      reviewDecisions: { orderBy: { decidedAt: 'desc' }, take: 20 },
      jobs: { where: { status: { in: [...activeJobs] } }, orderBy: { createdAt: 'desc' }, take: 1 },
    },
  }); if (!row) missing(); return view(row); }
  async edit(videoId: string, segmentId: string, expectedVersion: number, patch: SegmentPatch) { return this.prisma.$transaction(async (tx) => { const video = await tx.video.findUnique({ where: { id: videoId } }); if (!video) missing(); if (video.version !== expectedVersion) conflict(); const segment = await tx.videoSegment.findFirst({ where: { id: segmentId, videoId }, include: { currentRevision: true } }); if (!segment?.currentRevision) throw new StudioError('SEGMENT_NOT_FOUND', 'Segment was not found'); const current = segment.currentRevision; if (patch.targetStartMs !== undefined && patch.targetEndMs !== undefined && patch.targetEndMs <= patch.targetStartMs) throw new StudioError('STUDIO_VALIDATION_FAILED', 'Segment end must be after start'); if (patch.voiceProfileId && !await tx.voiceProfile.findFirst({ where: { id: patch.voiceProfileId, status: 'READY' } })) throw new StudioError('VOICE_NOT_READY', 'Voice is not ready'); const revision = await tx.segmentRevision.create({ data: { id: uuidV7(), videoSegmentId: segment.id, revision: current.revision + 1, sourceText: current.sourceText, translatedText: patch.translatedText ?? current.translatedText, castSheetEntryId: patch.castSheetEntryId === undefined ? current.castSheetEntryId : patch.castSheetEntryId, voiceProfileId: patch.voiceProfileId ?? current.voiceProfileId, targetStartMs: patch.targetStartMs ?? current.targetStartMs, targetEndMs: patch.targetEndMs ?? current.targetEndMs, speechRate: patch.speechRate ?? current.speechRate, editReason: patch.editReason ?? null, createdBy: OWNER_ID } }); await tx.segmentRevision.update({ where: { id: current.id }, data: { status: 'SUPERSEDED' } }); await tx.videoSegment.update({ where: { id: segment.id }, data: { currentRevisionId: revision.id } }); await tx.video.update({ where: { id: videoId }, data: { version: { increment: 1 }, status: 'AWAITING_REVIEW' } }); await tx.outboxMessage.create({ data: { id: uuidV7(), aggregateType: 'VIDEO', aggregateId: videoId, eventType: 'studio.invalidate', payloadSafe: { videoId, reason: 'SEGMENT_EDITED' } } }); return { videoId, segmentId, revisionId: revision.id, revision: revision.revision, version: video.version + 1 }; }, { isolationLevel: 'Serializable' }); }
  async previewAsset(videoId: string, segmentId: string) { const audio = await this.prisma.segmentAudioRevision.findFirst({ where: { videoSegmentId: segmentId, segment: { videoId }, status: { in: ['READY','SELECTED'] }, asset: { status: 'AVAILABLE', deletedAt: null } }, orderBy: { revision: 'desc' }, include: { asset: true } }); if (!audio?.asset) throw new StudioError('PREVIEW_NOT_AVAILABLE', 'Segment preview is not available'); return audio.asset; }
  async regenerate(videoId: string, segmentId: string, expectedVersion: number, key: string) { if (!await this.prisma.videoSegment.findFirst({ where: { id: segmentId, videoId }, select: { id: true } })) throw new StudioError('SEGMENT_NOT_FOUND', 'Segment was not found'); return this.createJob('STUDIO_REGENERATE_V1', videoId, expectedVersion, key, 'REGENERATE_SEGMENT', { segmentId }); }
  render(videoId: string, expectedVersion: number, key: string) { return this.createJob('STUDIO_RENDER_V1', videoId, expectedVersion, key, 'RENDER', {}); }
  async review(videoId: string, expectedVersion: number, input: ReviewInput) { return this.prisma.$transaction(async (tx) => { const video = await tx.video.findUnique({ where: { id: videoId } }); if (!video) missing(); if (video.version !== expectedVersion || input.subjectVersion !== String(video.version)) conflict(); const decision = await tx.reviewDecision.create({ data: { id: uuidV7(), videoId, scope: input.scope, subjectVersion: input.subjectVersion, decision: input.decision, note: input.note ?? null, decidedBy: OWNER_ID } }); const updated = await tx.video.update({ where: { id: videoId }, data: { version: { increment: 1 }, ...(input.decision === 'APPROVED' && input.scope === 'TTS' ? { status: 'READY_TO_PUBLISH' as const } : { status: 'AWAITING_REVIEW' as const }) } }); return { id: decision.id, ...input, note: input.note ?? null, decidedAt: decision.decidedAt.toISOString(), version: updated.version }; }); }
  private async createJob(scope: string, videoId: string, version: number, key: string, taskType: 'REGENERATE_SEGMENT'|'RENDER', extra: Record<string,string>) { const keyHash = createHash('sha256').update(key).digest('hex'); const requestHash = createHash('sha256').update(JSON.stringify({ videoId, version, ...extra })).digest('hex'); return this.prisma.$transaction(async (tx) => { const prior = await tx.idempotencyRecord.findUnique({ where: { scope_key: { scope, key: keyHash } } }); if (prior) { if (prior.requestHash !== requestHash) throw new StudioError('IDEMPOTENCY_KEY_REUSED', 'Idempotency-Key was used for another request'); return prior.responseBody as { jobId: string; taskId: string; version: number }; } const video = await tx.video.findUnique({ where: { id: videoId } }); if (!video) missing(); if (video.version !== version) conflict(); const reviewPolicy = await resolveReviewPolicySnapshot(tx, { channelProfileId: video.channelProfileId, seriesProfileId: video.seriesProfileId }); const jobId = uuidV7(); const taskId = uuidV7(); await tx.pipelineJob.create({ data: { id: jobId, videoId, kind: 'RERENDER', status: 'QUEUED', pipelineVersion: 'studio-v1', profileSnapshot: { studioVideoVersion: version, reviewPolicy }, requestedOutputs: { output16x9Enabled: true }, createdById: OWNER_ID, tasks: { create: { id: taskId, taskType, resourceClass: taskType === 'RENDER' ? 'GPU_BATCH' : 'GPU_TTS_INTERACTIVE', status: 'READY', readyAt: new Date(), inputManifest: { videoId, ...extra }, configuration: {} } } } }); const updated = await tx.video.update({ where: { id: videoId }, data: { status: 'PROCESSING', version: { increment: 1 } } }); const result = { jobId, taskId, version: updated.version }; await tx.idempotencyRecord.create({ data: { id: uuidV7(), scope, key: keyHash, requestHash, responseBody: result, responseEtag: `"${updated.version}"` } }); return result; }, { isolationLevel: 'Serializable' }); }
}
function missing(): never { throw new StudioError('VIDEO_NOT_FOUND', 'Video was not found'); }
function conflict(): never { throw new StudioError('VERSION_CONFLICT', 'Studio version is stale'); }
function view(row: any): StudioEnvelope['data'] { return { video: { id: row.id, version: row.version, title: row.displayTitle, status: row.status, sourceDurationMs: row.sourceContent.durationMs }, transcriptRuns: row.transcriptRuns.map((run: any) => ({ id: run.id, method: run.method, status: run.status, language: run.language, averageConfidence: run.averageConfidence?.toString() ?? null, selectedAt: run.selectedAt?.toISOString() ?? null })), cast: row.seriesProfile?.castSheet ? { id: row.seriesProfile.castSheet.id, status: row.seriesProfile.castSheet.status, version: row.seriesProfile.castSheet.version, entries: row.seriesProfile.castSheet.entries.map((entry: any) => ({ id: entry.id, characterKey: entry.characterKey, displayName: entry.displayName, roleKind: entry.roleKind, voice: { id: entry.voiceProfile.id, name: entry.voiceProfile.name } })) } : null, segments: row.segments.map((segment: any) => ({ id: segment.id, ordinal: segment.ordinal, sourceStartMs: segment.sourceStartMs, sourceEndMs: segment.sourceEndMs, revision: segment.currentRevision ? { id: segment.currentRevision.id, revision: segment.currentRevision.revision, sourceText: segment.currentRevision.sourceText, translatedText: segment.currentRevision.translatedText, targetStartMs: segment.currentRevision.targetStartMs, targetEndMs: segment.currentRevision.targetEndMs, speechRate: Number(segment.currentRevision.speechRate), status: segment.currentRevision.status, castSheetEntryId: segment.currentRevision.castSheetEntryId, voice: { id: segment.currentRevision.voiceProfile.id, name: segment.currentRevision.voiceProfile.name }, preview: segment.currentRevision.audioRevisions[0] ? { id: segment.currentRevision.audioRevisions[0].id, status: segment.currentRevision.audioRevisions[0].status, durationMs: segment.currentRevision.audioRevisions[0].actualDurationMs } : null } : null })), reviews: row.reviewDecisions.map((item: any) => ({ id: item.id, scope: item.scope, subjectVersion: item.subjectVersion, decision: item.decision, note: item.note, decidedAt: item.decidedAt.toISOString() })), capabilities: { canEdit: row.status !== 'ARCHIVED', canRegenerate: row.status !== 'ARCHIVED', canRender: row.segments.length > 0 && !row.jobs.length } }; }
