import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { DiscoveryItem, DiscoveryRunStatus, SourceAccount, Watchlist } from '@reup-dubbing-studio/api-client';
import { ExternalLinkIcon, ListFilterIcon, PlusIcon, RadarIcon, RefreshCwIcon, SearchIcon, Trash2Icon, UploadIcon } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button'; import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Switch } from '@/components/ui/switch';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'; import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'; import { Textarea } from '@/components/ui/textarea';
import { ListState } from '@/shared/ui/list-state';
import { DISPLAY_TIMEZONE } from '@/shared/lib/display-time';
import { useQuerySelection } from '@/shared/lib/use-query-selection';
import { IngestJobDialog } from '@/features/ingest/ui/ingest-job-dialog';
import { addSourceAccount, addWatchlist, DiscoveryApiError, removeWatchlist, saveSourceCookie, saveWatchlist, scanWatchlist, startDiscovery, stopDiscovery } from '../api/discovery-api';
import { categoriesQuery, discoveryItemsQuery, discoveryKeys, discoveryRunQuery, sourceAccountsQuery, watchlistsQuery } from '../api/discovery-query';

type Mode = 'JINGXUAN' | 'CREATOR' | 'WATCHLIST';
export function DiscoveryPage() {
  const client = useQueryClient(); const accounts = useQuery(sourceAccountsQuery()); const categories = useQuery(categoriesQuery()); const watchlists = useQuery(watchlistsQuery());
  const [selectedAccountId, setAccountId] = useQuerySelection('sourceAccountId'); const accountId = selectedAccountId ?? ''; const [mode, setMode] = useState<Mode>('JINGXUAN'); const [categoryId, setCategoryId] = useState('ALL'); const [creatorUrl, setCreatorUrl] = useState(''); const [runId, setRunId] = useState<string>(); const [contentType, setContentType] = useState('ALL'); const [availability, setAvailability] = useState('ALL'); const [eligible, setEligible] = useState('ALL'); const [selected, setSelected] = useState<Set<string>>(new Set()); const [credentialOpen, setCredentialOpen] = useState(false); const [watchlistOpen, setWatchlistOpen] = useState(false); const [ingestOpen, setIngestOpen] = useState(false);
  useEffect(() => { if (!accountId && accounts.data?.[0]) setAccountId(accounts.data[0].id); }, [accountId, accounts.data]);
  const run = useQuery({ ...discoveryRunQuery(runId ?? '00000000-0000-7000-8000-000000000000'), enabled: Boolean(runId) });
  const filters = useMemo(() => ({ ...(runId ? { runId } : {}), ...(categoryId !== 'ALL' ? { categoryId } : {}), ...(contentType !== 'ALL' ? { contentType: contentType as 'VIDEO' | 'LONG_VIDEO' | 'NOTE' | 'SLIDES' | 'ARTICLE' | 'LIVE' | 'UNKNOWN' } : {}), ...(availability !== 'ALL' ? { availability: availability as 'AVAILABLE' | 'PRIVATE' | 'REMOVED' | 'REGION_BLOCKED' | 'UNKNOWN' } : {}), ...(eligible !== 'ALL' ? { ingestEligible: eligible === 'YES' } : {}), limit: 50 }), [availability, categoryId, contentType, eligible, runId]);
  const results = useInfiniteQuery(discoveryItemsQuery(filters)); const items = useMemo(() => results.data?.pages.flatMap((page) => page.items) ?? [], [results.data]);
  useEffect(() => { if (run.data && ['SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED'].includes(run.data.status)) void client.invalidateQueries({ queryKey: discoveryKeys.items(filters) }); }, [client, filters, run.data]);
  const scan = useMutation({ mutationFn: () => startDiscovery(mode === 'CREATOR' ? { sourceAccountId: accountId, mode: 'CREATOR', input: creatorUrl, requestedLimit: 50 } : { sourceAccountId: accountId, mode: categoryId === 'ALL' ? 'JINGXUAN' : 'CATEGORY', ...(categoryId !== 'ALL' ? { categoryId } : {}), requestedLimit: 50 }), onSuccess: (created) => { setRunId(created.id); setSelected(new Set()); toast.success('Đã đưa lượt quét vào hàng đợi.'); }, onError: notify });
  const cancel = useMutation({ mutationFn: () => stopDiscovery(runId!), onSuccess: async () => { await client.invalidateQueries({ queryKey: discoveryKeys.run(runId!) }); toast.success('Đã hủy lượt quét.'); }, onError: notify });
  const activeAccount = accounts.data?.find((item) => item.id === accountId); const canScan = activeAccount?.status === 'ACTIVE' && (mode !== 'CREATOR' || creatorUrl.trim().length > 0);
  const selectedSources = items.filter((entry) => selected.has(entry.sourceContent.id)).map((entry) => ({ id: entry.sourceContent.id, title: entry.sourceContent.title ?? entry.sourceContent.externalId }));
  return <div className="page discovery-page"><header className="profiles-heading"><div><p className="eyebrow">Nguồn nội dung</p><h1>Khám phá video</h1><p className="lede">Quét metadata Douyin, chọn nội dung phù hợp và theo dõi tác giả mà chưa tải video.</p></div><Button variant="outline" onClick={() => setCredentialOpen(true)}><UploadIcon />Tài khoản & cookie</Button></header>
    <section className="discovery-source-card" aria-labelledby="discovery-source-title"><div className="discovery-source-head"><div><h2 id="discovery-source-title">Chọn nguồn quét</h2><p>Cookie chỉ gửi tới Control Plane để mã hóa; trình duyệt không lưu lại.</p></div><AccountHealth account={accounts.data?.find((item) => item.id === accountId)} /></div><div className="discovery-source-controls"><Select value={accountId} onValueChange={setAccountId}><SelectTrigger aria-label="Tài khoản nguồn"><SelectValue placeholder="Chọn tài khoản Douyin" /></SelectTrigger><SelectContent>{accounts.data?.map((account) => <SelectItem key={account.id} value={account.id}>{account.displayName}</SelectItem>)}</SelectContent></Select><Tabs value={mode} onValueChange={(value) => setMode(value as Mode)}><TabsList><TabsTrigger value="JINGXUAN">Jingxuan</TabsTrigger><TabsTrigger value="CREATOR">Tác giả</TabsTrigger><TabsTrigger value="WATCHLIST">Watchlist</TabsTrigger></TabsList><TabsContent value="JINGXUAN" className="sr-only">Nguồn Jingxuan</TabsContent><TabsContent value="CREATOR" className="sr-only">Nguồn tác giả</TabsContent><TabsContent value="WATCHLIST" className="sr-only">Nguồn watchlist</TabsContent></Tabs></div>{mode === 'JINGXUAN' && <div className="discovery-inline"><Select value={categoryId} onValueChange={setCategoryId}><SelectTrigger aria-label="Category"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Tất cả category</SelectItem>{categories.data?.filter((item) => item.slug !== 'all').map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select><Button disabled={!canScan || scan.isPending} onClick={() => scan.mutate()}><RadarIcon />{scan.isPending ? 'Đang tạo…' : 'Bắt đầu quét'}</Button></div>}{mode === 'CREATOR' && <div className="discovery-inline"><Input aria-label="URL tác giả Douyin" placeholder="https://www.douyin.com/user/…" value={creatorUrl} onChange={(event) => setCreatorUrl(event.target.value)} /><Button disabled={!canScan || scan.isPending} onClick={() => scan.mutate()}><SearchIcon />Quét tác giả</Button><Button variant="outline" disabled={!accountId || !creatorUrl.trim()} onClick={() => setWatchlistOpen(true)}><PlusIcon />Thêm watchlist</Button></div>}{mode === 'WATCHLIST' && <WatchlistPanel items={watchlists.data ?? []} onAdd={() => setWatchlistOpen(true)} />}</section>
    {mode !== 'WATCHLIST' && <><RunBanner status={run.data?.status} itemCount={run.data?.itemCount} error={run.data?.errorDetail} onCancel={() => cancel.mutate()} /><section className="profiles-toolbar discovery-filters" aria-label="Bộ lọc kết quả"><ListFilterIcon /><Select value={contentType} onValueChange={setContentType}><SelectTrigger aria-label="Loại nội dung"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Mọi loại</SelectItem><SelectItem value="VIDEO">Video</SelectItem><SelectItem value="LONG_VIDEO">Video dài</SelectItem><SelectItem value="NOTE">Note</SelectItem><SelectItem value="SLIDES">Slides</SelectItem></SelectContent></Select><Select value={availability} onValueChange={setAvailability}><SelectTrigger aria-label="Khả dụng"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Mọi trạng thái</SelectItem><SelectItem value="AVAILABLE">Khả dụng</SelectItem><SelectItem value="PRIVATE">Riêng tư</SelectItem><SelectItem value="REMOVED">Đã gỡ</SelectItem><SelectItem value="REGION_BLOCKED">Chặn vùng</SelectItem></SelectContent></Select><Select value={eligible} onValueChange={setEligible}><SelectTrigger aria-label="Điều kiện ingest"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Mọi khả năng ingest</SelectItem><SelectItem value="YES">Có thể ingest</SelectItem><SelectItem value="NO">Chưa hỗ trợ ingest</SelectItem></SelectContent></Select>{selected.size > 0 && <Badge>{selected.size} đã chọn</Badge>}</section><Results items={items} query={results} selected={selected} onSelected={setSelected} />{selected.size > 0 && <div className="discovery-selection-bar" role="region" aria-label="Thao tác với nội dung đã chọn"><div><strong>{selected.size} video đã chọn</strong><span>Kiểm tra trùng trước khi tạo job tải.</span></div><Button disabled={activeAccount?.status !== 'ACTIVE'} onClick={() => setIngestOpen(true)}><PlusIcon />Tạo job từ {selected.size} video</Button></div>}</>}
    <CredentialDialog open={credentialOpen} accounts={accounts.data ?? []} onOpenChange={setCredentialOpen} /><WatchlistDialog open={watchlistOpen} accountId={accountId} initialUrl={creatorUrl} onOpenChange={setWatchlistOpen} /><IngestJobDialog open={ingestOpen} sourceAccountId={accountId} sources={selectedSources} onOpenChange={setIngestOpen} /></div>;
}

function Results({ items, query, selected, onSelected }: { items: DiscoveryItem[]; query: ReturnType<typeof useInfiniteQuery>; selected: Set<string>; onSelected: (value: Set<string>) => void }) { if (query.isPending) return <ListState state="loading" title="Đang tải kết quả" description="Đọc source content đã lưu từ Control Plane…" />; if (query.isError) return <ListState state="error" title="Không thể tải kết quả" description="Kiểm tra kết nối rồi thử lại." action={<Button onClick={() => void query.refetch()}>Thử lại</Button>} />; if (!items.length) return <ListState state="empty" title="Chưa có kết quả" description="Chọn nguồn và bắt đầu quét metadata." />; const all = items.every((item) => selected.has(item.sourceContent.id)); return <><div className="profiles-table discovery-table"><Table><TableHeader><TableRow><TableHead><Checkbox aria-label="Chọn tất cả kết quả" checked={all} onCheckedChange={(checked) => onSelected(checked ? new Set(items.map((item) => item.sourceContent.id)) : new Set())} /></TableHead><TableHead>Nội dung</TableHead><TableHead>Tác giả</TableHead><TableHead>Loại</TableHead><TableHead>Chỉ số</TableHead><TableHead>Trạng thái</TableHead><TableHead><span className="sr-only">Mở nguồn</span></TableHead></TableRow></TableHeader><TableBody>{items.map((entry) => { const content = entry.sourceContent; return <TableRow key={entry.id}><TableCell><Checkbox aria-label={`Chọn ${content.title ?? content.externalId}`} checked={selected.has(content.id)} onCheckedChange={(checked) => { const next = new Set(selected); if (checked) next.add(content.id); else next.delete(content.id); onSelected(next); }} /></TableCell><TableCell><div className="discovery-content-cell">{content.cover?.url && <img src={content.cover.url} alt="" loading="lazy" />}<div><strong>{content.title ?? 'Không có tiêu đề'}</strong><span>{formatDate(content.publishedAt ?? content.firstSeenAt)}</span></div></div></TableCell><TableCell>{content.creator?.nickname ?? content.creator?.externalId ?? '—'}</TableCell><TableCell><Badge variant="outline">{content.contentType}</Badge></TableCell><TableCell>{compact(content.metrics?.playCount)} xem · {compact(content.metrics?.diggCount)} thích</TableCell><TableCell><Badge variant={content.ingestEligible && content.availability === 'AVAILABLE' ? 'default' : 'secondary'}>{content.availability !== 'AVAILABLE' ? content.availability : content.ingestEligible ? 'Sẵn sàng' : 'Chưa hỗ trợ'}</Badge></TableCell><TableCell>{content.canonicalUrl && <Button asChild size="icon" variant="ghost"><a href={content.canonicalUrl} target="_blank" rel="noreferrer" aria-label="Mở nội dung nguồn"><ExternalLinkIcon /></a></Button>}</TableCell></TableRow>; })}</TableBody></Table></div>{query.hasNextPage && <div className="profiles-load-more"><Button variant="outline" onClick={() => void query.fetchNextPage()}>Tải thêm</Button></div>}</>; }
function RunBanner({ status, itemCount, error, onCancel }: { status: DiscoveryRunStatus | undefined; itemCount: number | undefined; error: string | null | undefined; onCancel: () => void }) { if (!status) return null; const active = status === 'QUEUED' || status === 'RUNNING'; return <div className="discovery-run-banner" role="status"><div><Badge variant={status === 'FAILED' ? 'destructive' : status === 'PARTIAL' ? 'secondary' : 'outline'}>{status}</Badge><span>{active ? 'Đang quét metadata…' : `Đã ghi nhận ${itemCount ?? 0} nội dung.`}{error ? ` ${error}` : ''}</span></div>{active && <Button size="sm" variant="outline" onClick={onCancel}>Hủy</Button>}</div>; }
function AccountHealth({ account }: { account: SourceAccount | undefined }) { if (!account) return <Badge variant="outline">Chưa chọn tài khoản</Badge>; return <Badge variant={account.status === 'ACTIVE' ? 'default' : 'destructive'}>{account.status === 'ACTIVE' ? 'Cookie hoạt động' : account.status}</Badge>; }
function CredentialDialog({ open, accounts, onOpenChange }: { open: boolean; accounts: SourceAccount[]; onOpenChange: (open: boolean) => void }) { const client = useQueryClient(); const [name, setName] = useState('Douyin chính'); const [accountId, setAccountId] = useState('NEW'); const [cookie, setCookie] = useState(''); const mutation = useMutation({ mutationFn: async () => { const id = accountId === 'NEW' ? (await addSourceAccount(name)).id : accountId; return saveSourceCookie(id, cookie); }, onSuccess: async () => { await client.invalidateQueries({ queryKey: discoveryKeys.accounts() }); setCookie(''); onOpenChange(false); toast.success('Cookie đã được mã hóa và lưu.'); }, onError: notify }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Tài khoản nguồn Douyin</DialogTitle><DialogDescription>Nhập Netscape cookie. Giá trị sẽ không được hiển thị lại hoặc lưu trong trình duyệt.</DialogDescription></DialogHeader><div className="discovery-form"><Label htmlFor="source-account">Tài khoản</Label><Select value={accountId} onValueChange={setAccountId}><SelectTrigger id="source-account"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="NEW">Tạo tài khoản mới</SelectItem>{accounts.map((account) => <SelectItem key={account.id} value={account.id}>{account.displayName}</SelectItem>)}</SelectContent></Select>{accountId === 'NEW' && <><Label htmlFor="source-name">Tên hiển thị</Label><Input id="source-name" value={name} onChange={(event) => setName(event.target.value)} /></>}<Label htmlFor="source-cookie">Netscape cookie</Label><Textarea id="source-cookie" className="min-h-40 font-mono text-xs" value={cookie} onChange={(event) => setCookie(event.target.value)} autoComplete="off" /></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Hủy</Button><Button disabled={!cookie.trim() || mutation.isPending || (accountId === 'NEW' && !name.trim())} onClick={() => mutation.mutate()}>Lưu an toàn</Button></DialogFooter></DialogContent></Dialog>; }
function WatchlistDialog({ open, accountId, initialUrl, onOpenChange }: { open: boolean; accountId: string; initialUrl: string; onOpenChange: (open: boolean) => void }) { const client = useQueryClient(); const [url, setUrl] = useState(initialUrl); const [name, setName] = useState(''); useEffect(() => { if (open) setUrl(initialUrl); }, [initialUrl, open]); const mutation = useMutation({ mutationFn: () => addWatchlist({ sourceAccountId: accountId, input: url, displayName: name, scheduleIntervalMin: 60 }), onSuccess: async () => { await client.invalidateQueries({ queryKey: discoveryKeys.watchlists() }); onOpenChange(false); toast.success('Đã thêm watchlist.'); }, onError: notify }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Thêm tác giả vào watchlist</DialogTitle><DialogDescription>Tự quét chỉ thu metadata, không tự tải video.</DialogDescription></DialogHeader><div className="discovery-form"><Label htmlFor="watch-name">Tên watchlist</Label><Input id="watch-name" value={name} onChange={(event) => setName(event.target.value)} /><Label htmlFor="watch-url">URL tác giả Douyin</Label><Input id="watch-url" value={url} onChange={(event) => setUrl(event.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Hủy</Button><Button disabled={!accountId || !name.trim() || !url.trim() || mutation.isPending} onClick={() => mutation.mutate()}>Thêm watchlist</Button></DialogFooter></DialogContent></Dialog>; }
function WatchlistPanel({ items, onAdd }: { items: Watchlist[]; onAdd: () => void }) { const client = useQueryClient(); const [remove, setRemove] = useState<Watchlist>(); const refresh = () => client.invalidateQueries({ queryKey: discoveryKeys.watchlists() }); const toggle = useMutation({ mutationFn: (item: Watchlist) => saveWatchlist(item.id, item.version, { status: item.status === 'ACTIVE' ? 'PAUSED' : 'ACTIVE' }), onSuccess: async () => { await refresh(); toast.success('Đã cập nhật watchlist.'); }, onError: notify }); const scan = useMutation({ mutationFn: scanWatchlist, onSuccess: () => toast.success('Đã đưa watchlist vào hàng đợi quét.'), onError: notify }); const deletion = useMutation({ mutationFn: (item: Watchlist) => removeWatchlist(item.id, item.version), onSuccess: async () => { await refresh(); setRemove(undefined); toast.success('Đã xóa watchlist.'); }, onError: notify }); return <div className="watchlist-panel"><div className="watchlist-panel-head"><p>{items.length} nguồn đang theo dõi</p><Button size="sm" variant="outline" onClick={onAdd}><PlusIcon />Thêm nguồn</Button></div>{items.length ? items.map((item) => <article className="watchlist-row" key={item.id}><div><strong>{item.displayName}</strong><span>{String(item.resolvedInput.url ?? '')}</span></div><Badge variant={item.status === 'ACTIVE' ? 'default' : 'secondary'}>{item.status}</Badge><span>{item.lastSuccessAt ? formatDate(item.lastSuccessAt) : 'Chưa quét'}</span><Switch aria-label={`Tự quét ${item.displayName}`} checked={item.status === 'ACTIVE'} onCheckedChange={() => toggle.mutate(item)} /><Button size="sm" variant="outline" disabled={scan.isPending} onClick={() => scan.mutate(item.id)}><RefreshCwIcon />Quét</Button><Button size="icon" variant="ghost" aria-label={`Xóa ${item.displayName}`} onClick={() => setRemove(item)}><Trash2Icon /></Button></article>) : <ListState state="empty" title="Chưa có watchlist" description="Thêm URL tác giả Douyin để theo dõi nội dung mới." />}<AlertDialog open={Boolean(remove)} onOpenChange={(value) => { if (!value) setRemove(undefined); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xóa watchlist?</AlertDialogTitle><AlertDialogDescription>Chỉ xóa nguồn theo dõi, không xóa source content đã khám phá.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Hủy</AlertDialogCancel><AlertDialogAction onClick={() => remove && deletion.mutate(remove)}>Xóa</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>; }
function notify(error: unknown) { toast.error(error instanceof DiscoveryApiError ? error.message : 'Không thể hoàn tất thao tác.'); }
function compact(value?: string | null) { if (!value) return '—'; return new Intl.NumberFormat('vi-VN', { notation: 'compact' }).format(Number(value)); }
function formatDate(value: string) { return new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeStyle: 'short', timeZone: DISPLAY_TIMEZONE }).format(new Date(value)); }
