import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { VoiceProfile, VoiceProfileStatus } from '@reup-dubbing-studio/api-client';
import { ArchiveIcon, CheckCircle2Icon, PencilIcon, PlayIcon, PlusIcon, RotateCcwIcon, SearchIcon } from 'lucide-react';
import { useMemo, useState } from 'react';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'; import { ListState } from '@/shared/ui/list-state';
import { activateVoice, changeVoiceArchive, fetchSamplePreview, VoicesApiError, type VoiceSnapshot } from '../api/voices-api';
import { voiceDetailQuery, voiceKeys, voicesQuery, type VoiceQueryFilters } from '../api/voices-query'; import { VoiceDialog } from './voice-dialog';
const EMPTY = '00000000-0000-7000-8000-000000000000';
export function VoicesPage() {
  const client = useQueryClient(); const [query, setQuery] = useState(''); const [status, setStatus] = useState<VoiceProfileStatus | 'ALL'>('ALL'); const [language, setLanguage] = useState(''); const [tag, setTag] = useState(''); const [commercial, setCommercial] = useState<'ALL' | 'YES' | 'NO'>('ALL'); const [selected, setSelected] = useState<string | null>(null); const [dialog, setDialog] = useState(false);
  const filters: VoiceQueryFilters = { query, status, language, tag, commercial }; const list = useInfiniteQuery(voicesQuery(filters)); const voices = useMemo(() => list.data?.pages.flatMap((page) => page.items) ?? [], [list.data]); const detail = useQuery({ ...voiceDetailQuery(selected ?? EMPTY), enabled: Boolean(selected) });
  const action = useMutation({ mutationFn: async (kind: 'activate' | 'archive') => { if (!detail.data) throw new Error(); return kind === 'activate' ? activateVoice(detail.data.profile.id, detail.data.etag) : changeVoiceArchive(detail.data.profile.id, detail.data.etag, detail.data.profile.status === 'ARCHIVED' ? 'restore' : 'archive'); }, onSuccess: async (_, kind) => { await client.invalidateQueries({ queryKey: voiceKeys.all }); toast.success(kind === 'activate' ? 'Voice đã sẵn sàng.' : 'Đã cập nhật trạng thái Voice.'); }, onError: async (error) => { if (error instanceof VoicesApiError && error.code === 'VOICE_VERSION_CONFLICT') await client.invalidateQueries({ queryKey: voiceKeys.all }); toast.error(error instanceof VoicesApiError ? error.message : 'Không thể cập nhật Voice.'); } });
  return <div className="page voices-page"><header className="profiles-heading"><div><p className="eyebrow">Tài nguyên</p><h1>Thư viện giọng</h1><p className="lede">Quản lý quyền sử dụng, ngôn ngữ và reference sample cho pipeline lồng tiếng.</p></div><Button onClick={() => { setSelected(null); setDialog(true); }}><PlusIcon />Tạo Voice</Button></header><section className="profiles-toolbar" aria-label="Bộ lọc giọng"><div className="profiles-search"><SearchIcon /><Input aria-label="Tìm giọng" placeholder="Tìm theo tên…" value={query} onChange={(event) => setQuery(event.target.value)} /></div><Select value={status} onValueChange={(value) => setStatus(value as typeof status)}><SelectTrigger aria-label="Lọc trạng thái"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Mọi trạng thái</SelectItem><SelectItem value="DRAFT">Bản nháp</SelectItem><SelectItem value="READY">Sẵn sàng</SelectItem><SelectItem value="BLOCKED_LICENSE">Chặn license</SelectItem><SelectItem value="ARCHIVED">Đã lưu trữ</SelectItem></SelectContent></Select><Input aria-label="Lọc ngôn ngữ" placeholder="Ngôn ngữ (vi)" value={language} onChange={(event) => setLanguage(event.target.value)} /><Input aria-label="Lọc tag" placeholder="Tag" value={tag} onChange={(event) => setTag(event.target.value)} /><Select value={commercial} onValueChange={(value) => setCommercial(value as typeof commercial)}><SelectTrigger aria-label="Lọc quyền sử dụng"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Mọi quyền</SelectItem><SelectItem value="YES">Được thương mại</SelectItem><SelectItem value="NO">Không thương mại</SelectItem></SelectContent></Select></section>
    {list.isPending ? <ListState state="loading" title="Đang tải giọng" description="Đang đồng bộ từ Control Plane…" /> : list.isError ? <ListState state="error" title="Không thể tải giọng" description="Thử lại kết nối Control Plane." action={<Button onClick={() => void list.refetch()}>Thử lại</Button>} /> : !voices.length ? <ListState state="empty" title="Chưa có giọng phù hợp" description="Thay đổi bộ lọc hoặc tạo Voice đầu tiên." /> : <VoiceTable voices={voices} onSelect={setSelected} />}{list.hasNextPage && <div className="profiles-load-more"><Button variant="outline" onClick={() => void list.fetchNextPage()}>Tải thêm</Button></div>}
    <VoiceSheet snapshot={detail.data} open={Boolean(selected)} loading={detail.isPending} onOpenChange={(open) => { if (!open) setSelected(null); }} onEdit={() => setDialog(true)} onAction={(kind) => action.mutate(kind)} pending={action.isPending} /><VoiceDialog open={dialog} snapshot={selected ? detail.data ?? null : null} onOpenChange={setDialog} /></div>;
}
function VoiceTable({ voices, onSelect }: { voices: VoiceProfile[]; onSelect: (id: string) => void }) { return <div className="profiles-table"><Table><TableHeader><TableRow><TableHead>Voice</TableHead><TableHead>Ngôn ngữ</TableHead><TableHead>License</TableHead><TableHead>Trạng thái</TableHead><TableHead>Sample</TableHead><TableHead>Cập nhật</TableHead></TableRow></TableHeader><TableBody>{voices.map((voice) => <TableRow key={voice.id} tabIndex={0} className="cursor-pointer" onClick={() => onSelect(voice.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onSelect(voice.id); }}><TableCell><strong>{voice.name}</strong><div className="voice-tags">{voice.tags.map((tag) => <Badge key={tag} variant="secondary">{tag}</Badge>)}</div></TableCell><TableCell>{voice.primaryLanguage}</TableCell><TableCell>{licenseLabel(voice.licenseKind)}</TableCell><TableCell><VoiceStatus status={voice.status} /></TableCell><TableCell>{voice.samples.length}</TableCell><TableCell>{new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium' }).format(new Date(voice.updatedAt))}</TableCell></TableRow>)}</TableBody></Table></div>; }
function VoiceSheet({ snapshot, open, loading, onOpenChange, onEdit, onAction, pending }: { snapshot?: VoiceSnapshot | undefined; open: boolean; loading: boolean; onOpenChange: (open: boolean) => void; onEdit: () => void; onAction: (kind: 'activate' | 'archive') => void; pending: boolean }) { const voice = snapshot?.profile; return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="profile-sheet overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{voice?.name ?? 'Chi tiết Voice'}</SheetTitle><SheetDescription>Quyền sử dụng, dependency và sample hiện hành.</SheetDescription></SheetHeader>{loading ? <ListState state="loading" title="Đang tải chi tiết" description="Đang lấy version mới nhất…" /> : voice ? <div className="profile-details"><div className="profile-detail-summary"><VoiceStatus status={voice.status} /><Badge variant={voice.readiness === 'READY' ? 'default' : 'secondary'}>{voice.readiness === 'READY' ? 'Đủ cấu hình' : 'Cần cấu hình'}</Badge><span>Version {voice.version}</span></div><dl><Row label="Ngôn ngữ" value={voice.primaryLanguage} /><Row label="License" value={licenseLabel(voice.licenseKind)} /><Row label="Dùng thương mại" value={voice.commercialUseAllowed ? 'Có' : 'Không'} /><Row label="Đang được dùng" value={`${voice.referencedBy.channelProfiles} channel · ${voice.referencedBy.seriesProfiles} series`} /></dl>{voice.readinessIssues.length > 0 && <section><h3>Cần xử lý</h3><ul>{voice.readinessIssues.map((item) => <li key={item}>{item}</li>)}</ul></section>}<section><h3>Reference samples</h3>{voice.samples.length ? voice.samples.map((sample) => <SamplePlayer key={sample.id} voiceId={voice.id} sample={sample} />) : <p>Chưa có sample.</p>}</section></div> : null}{voice && <SheetFooter><Button variant="outline" disabled={pending} onClick={() => onAction('archive')}>{voice.status === 'ARCHIVED' ? <RotateCcwIcon /> : <ArchiveIcon />}{voice.status === 'ARCHIVED' ? 'Khôi phục' : 'Lưu trữ'}</Button>{voice.status !== 'ARCHIVED' && <><Button variant="outline" onClick={onEdit}><PencilIcon />Chỉnh sửa</Button>{voice.status !== 'READY' && <Button disabled={pending} onClick={() => onAction('activate')}><CheckCircle2Icon />Kích hoạt</Button>}</>}</SheetFooter>}</SheetContent></Sheet>; }
function SamplePlayer({ voiceId, sample }: { voiceId: string; sample: VoiceProfile['samples'][number] }) { const [url, setUrl] = useState<string>(); const [loading, setLoading] = useState(false); const play = async () => { setLoading(true); try { setUrl((await fetchSamplePreview(voiceId, sample.id)).url); } catch { toast.error('Không thể tải sample.'); } finally { setLoading(false); } }; return <article className="voice-sample"><div><strong>{sample.language} · revision {sample.revision}</strong><p>{sample.transcript}</p></div>{url ? <audio className="voice-audio" controls autoPlay src={url}>Trình duyệt không hỗ trợ audio.</audio> : <Button size="sm" variant="outline" disabled={loading} onClick={() => void play()}><PlayIcon />{loading ? 'Đang tải…' : 'Nghe sample'}</Button>}</article>; }
function Row({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; } function VoiceStatus({ status }: { status: VoiceProfileStatus }) { return <Badge variant={status === 'READY' ? 'default' : status === 'BLOCKED_LICENSE' ? 'destructive' : 'outline'}>{{ DRAFT: 'Bản nháp', READY: 'Sẵn sàng', BLOCKED_LICENSE: 'Chặn license', ARCHIVED: 'Đã lưu trữ' }[status]}</Badge>; } function licenseLabel(value: VoiceProfile['licenseKind']) { return ({ OWNED_RECORDING: 'Bản ghi sở hữu', AUTHORIZED_COMMERCIAL: 'Ủy quyền thương mại', CC_BY: 'CC BY', CC_BY_NC: 'CC BY-NC', CUSTOM: 'Tùy chỉnh', UNKNOWN: 'Chưa rõ' } as const)[value]; }
