import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { PublicationTask, PublicationTaskStatus, PublishingPlatform } from '@reup-dubbing-studio/api-client';
import { CalendarDaysIcon, CheckIcon, ClipboardIcon, DownloadIcon, ExternalLinkIcon, ListIcon, LockIcon, RefreshCwIcon, RotateCcwIcon, SendIcon, UnlockIcon } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { toast } from 'sonner';

import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { ListState } from '@/shared/ui/list-state';
import {
  approvePublicationTask, PublishingApiError, reopenPublicationRevision, requestPublicationDownload,
  savePublicationField, savePublicationPlan, setPublicationChecklist, setPublicationFieldLock,
  startPublicationPosting, submitPublicationProof, verifyProof, type PublicationTaskItem,
} from '../api/publishing-api';
import { publicationTaskQuery, publicationTasksQuery, publishingKeys } from '../api/publishing-query';

const EMPTY_ID = '00000000-0000-7000-8000-000000000000';
const STATUSES: PublicationTaskStatus[] = ['READY_FOR_CONTENT', 'CONTENT_GENERATED', 'READY_TO_PUBLISH', 'POSTING_MANUAL', 'PUBLISHED', 'VERIFIED', 'NEEDS_REVISION', 'CANCELLED'];
type ViewMode = 'list'|'calendar';

export function PublishingPage() {
  const [status, setStatus] = useState<PublicationTaskStatus | 'ALL'>('ALL');
  const [platform, setPlatform] = useState<PublishingPlatform | 'ALL'>('ALL');
  const [scheduled, setScheduled] = useState<'ALL'|'YES'|'NO'>('ALL');
  const [view, setView] = useState<ViewMode>('list');
  const [selected, setSelected] = useState<string | null>(null);
  const filters = useMemo(() => ({ limit: 50, ...(status !== 'ALL' ? { status } : {}), ...(platform !== 'ALL' ? { platform } : {}), ...(scheduled !== 'ALL' ? { scheduled: scheduled === 'YES' } : {}) }), [platform, scheduled, status]);
  const list = useInfiniteQuery(publicationTasksQuery(filters));
  const tasks = useMemo(() => list.data?.pages.flatMap((page) => page.items) ?? [], [list.data]);

  const reset = () => { setStatus('ALL'); setPlatform('ALL'); setScheduled('ALL'); };
  return <div className="page publishing-page">
    <header className="publishing-heading"><div><p className="eyebrow">Không gian làm việc</p><h1>Bàn đăng bài</h1><p className="lede">Chuẩn bị metadata, tải asset và ghi nhận bằng chứng cho quy trình đăng YouTube/Facebook thủ công.</p></div><Button variant="outline" onClick={() => void list.refetch()} disabled={list.isFetching}><RefreshCwIcon className={list.isFetching ? 'animate-spin' : ''} />Làm mới</Button></header>
    <section className="publishing-summary" aria-label="Tóm tắt task đã tải">{statusSummary(tasks).map((item) => <button key={item.status} type="button" className={status === item.status ? 'is-active' : ''} onClick={() => setStatus(status === item.status ? 'ALL' : item.status)}><span className={`publishing-dot tone-${statusTone(item.status)}`} /><span>{statusLabel(item.status)}</span><strong>{item.count}</strong></button>)}</section>
    <section className="publishing-toolbar" aria-label="Bộ lọc bàn đăng bài"><label><span>Trạng thái</span><NativeSelect value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><NativeSelectOption value="ALL">Mọi trạng thái</NativeSelectOption>{STATUSES.map((value) => <NativeSelectOption key={value} value={value}>{statusLabel(value)}</NativeSelectOption>)}</NativeSelect></label><label><span>Nền tảng</span><NativeSelect value={platform} onChange={(event) => setPlatform(event.target.value as typeof platform)}><NativeSelectOption value="ALL">Mọi nền tảng</NativeSelectOption><NativeSelectOption value="YOUTUBE">YouTube</NativeSelectOption><NativeSelectOption value="FACEBOOK">Facebook</NativeSelectOption></NativeSelect></label><label><span>Lịch đăng</span><NativeSelect value={scheduled} onChange={(event) => setScheduled(event.target.value as typeof scheduled)}><NativeSelectOption value="ALL">Tất cả</NativeSelectOption><NativeSelectOption value="YES">Đã lên lịch</NativeSelectOption><NativeSelectOption value="NO">Chưa lên lịch</NativeSelectOption></NativeSelect></label><Button variant="outline" onClick={reset}>Đặt lại</Button><Tabs value={view} onValueChange={(value) => setView(value as ViewMode)}><TabsList aria-label="Kiểu hiển thị"><TabsTrigger value="list"><ListIcon />Danh sách</TabsTrigger><TabsTrigger value="calendar"><CalendarDaysIcon />Lịch</TabsTrigger></TabsList></Tabs></section>
    {list.isPending ? <ListState state="loading" title="Đang tải bàn đăng bài" description="Đang lấy publication task mới nhất…" /> : list.isError ? <ListState state="error" title="Không thể tải publication task" description={safeMessage(list.error)} action={<Button onClick={() => void list.refetch()}>Thử lại</Button>} /> : !tasks.length ? <ListState state="empty" title="Chưa có task phù hợp" description="Package đăng bài sẽ xuất hiện sau khi output render đã được duyệt." /> : view === 'list' ? <PublishingList tasks={tasks} onSelect={setSelected} /> : <PublishingCalendar tasks={tasks} onSelect={setSelected} />}
    {list.hasNextPage && <div className="publishing-more"><Button variant="outline" disabled={list.isFetchingNextPage} onClick={() => void list.fetchNextPage()}>{list.isFetchingNextPage ? 'Đang tải…' : 'Tải thêm'}</Button></div>}
    <PublicationTaskSheet id={selected} onClose={() => setSelected(null)} />
  </div>;
}

function PublishingList({ tasks, onSelect }: { tasks: PublicationTaskItem[]; onSelect: (id: string) => void }) {
  return <Card className="publishing-list"><CardHeader><CardTitle>Publication tasks</CardTitle><CardDescription>{tasks.length} task đã tải · thời gian hiển thị theo múi giờ Việt Nam</CardDescription></CardHeader><CardContent className="p-0"><div className="publishing-table"><Table><TableHeader><TableRow><TableHead>Video / destination</TableHead><TableHead>Trạng thái</TableHead><TableHead>Lịch đăng</TableHead><TableHead>Deadline</TableHead><TableHead>Output</TableHead><TableHead><span className="sr-only">Thao tác</span></TableHead></TableRow></TableHeader><TableBody>{tasks.map((task) => <TableRow key={task.id}><TableCell><div className="publishing-identity"><strong>{task.destinationName}</strong><span>{task.platform} · video {shortId(task.videoId)}</span></div></TableCell><TableCell><TaskStatus value={task.status} /></TableCell><TableCell>{formatDate(task.scheduledAt)}</TableCell><TableCell>{task.deadlineAt ? <span className={isOverdue(task) ? 'publishing-overdue' : ''}>{formatDate(task.deadlineAt)}</span> : '—'}</TableCell><TableCell><code>{shortId(task.renderOutputId)}</code></TableCell><TableCell><Button size="sm" variant="outline" onClick={() => onSelect(task.id)}>Mở task</Button></TableCell></TableRow>)}</TableBody></Table></div><div className="publishing-cards">{tasks.map((task) => <article key={task.id}><div><TaskStatus value={task.status} /><Badge variant="outline">{task.platform}</Badge></div><h2>{task.destinationName}</h2><code>Video {shortId(task.videoId)}</code><dl><div><dt>Lịch đăng</dt><dd>{formatDate(task.scheduledAt)}</dd></div><div><dt>Deadline</dt><dd>{formatDate(task.deadlineAt)}</dd></div></dl><Button variant="outline" onClick={() => onSelect(task.id)}>Mở task</Button></article>)}</div></CardContent></Card>;
}

function PublishingCalendar({ tasks, onSelect }: { tasks: PublicationTaskItem[]; onSelect: (id: string) => void }) {
  const groups = groupByDate(tasks);
  return <section className="publishing-calendar" aria-label="Lịch đăng thủ công">{groups.map(([date, items]) => <Card key={date}><CardHeader><CardTitle>{date === 'unscheduled' ? 'Chưa lên lịch' : formatDay(date)}</CardTitle><CardDescription>{items.length} task</CardDescription></CardHeader><CardContent>{items.map((task) => <button type="button" key={task.id} onClick={() => onSelect(task.id)}><span className={`publishing-platform platform-${task.platform.toLowerCase()}`}>{task.platform}</span><strong>{task.destinationName}</strong><span>{task.scheduledAt ? formatTime(task.scheduledAt) : 'Chọn thời gian trong task'}</span><TaskStatus value={task.status} /></button>)}</CardContent></Card>)}</section>;
}

function PublicationTaskSheet({ id, onClose }: { id: string | null; onClose: () => void }) {
  const client = useQueryClient();
  const detail = useQuery({ ...publicationTaskQuery(id ?? EMPTY_ID), enabled: Boolean(id) });
  const [fields, setFields] = useState<Record<string, string>>({});
  const [scheduledAt, setScheduledAt] = useState(''); const [deadlineAt, setDeadlineAt] = useState(''); const [notes, setNotes] = useState('');
  const [proofUrl, setProofUrl] = useState(''); const [postId, setPostId] = useState('');
  const [discardOpen, setDiscardOpen] = useState(false); const loadedRef = useRef<string | null>(null); const keyRef = useRef(crypto.randomUUID());
  const task = detail.data;
  const draftDirty = task ? task.fields.some((field) => (fields[field.key] ?? '') !== (field.currentRevision?.value ?? '')) || scheduledAt !== toLocalInput(task.scheduledAt) || deadlineAt !== toLocalInput(task.deadlineAt) || notes !== (task.notes ?? '') : false;

  useEffect(() => { if (!task || (loadedRef.current === task.id && draftDirty)) return; loadedRef.current = task.id; setFields(Object.fromEntries(task.fields.map((field) => [field.key, field.currentRevision?.value ?? '']))); setScheduledAt(toLocalInput(task.scheduledAt)); setDeadlineAt(toLocalInput(task.deadlineAt)); setNotes(task.notes ?? ''); }, [draftDirty, task]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (draftDirty) event.preventDefault(); }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [draftDirty]);

  const sync = async (updated: PublicationTask, message: string) => { client.setQueryData(publishingKeys.detail(updated.id), updated); loadedRef.current = null; keyRef.current = crypto.randomUUID(); await client.invalidateQueries({ queryKey: publishingKeys.lists() }); toast.success(message); };
  const action = useMutation({ mutationFn: async (input: { kind: string; fieldKey?: string; role?: 'VIDEO'|'SUBTITLE'|'THUMBNAIL'; proofId?: string }) => { if (!task) throw new Error('Task chưa sẵn sàng'); const key = keyRef.current; switch (input.kind) { case 'field': return savePublicationField(task, input.fieldKey!, fields[input.fieldKey!] ?? ''); case 'lock': { const field = task.fields.find((item) => item.key === input.fieldKey)!; return setPublicationFieldLock(task, field.key, !field.isLocked); } case 'plan': return savePublicationPlan(task, { scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : null, deadlineAt: deadlineAt ? new Date(deadlineAt).toISOString() : null, notes: notes.trim() || null }); case 'approve': return approvePublicationTask(task, key); case 'start': return startPublicationPosting(task, key); case 'proof': return submitPublicationProof(task, { publicUrl: proofUrl.trim() || null, platformPostId: postId.trim() || null }, key); case 'verify': return verifyProof(task, input.proofId!, 'VERIFIED', key); case 'fail-proof': return verifyProof(task, input.proofId!, 'FAILED', key); case 'revision': return reopenPublicationRevision(task, key); default: throw new Error('Hành động không hợp lệ'); } }, onSuccess: async (updated, input) => { if (input.kind === 'proof') { setProofUrl(''); setPostId(''); } await sync(updated, actionMessage(input.kind)); }, onError: async (error) => { keyRef.current = crypto.randomUUID(); if (error instanceof PublishingApiError && error.code === 'PUBLICATION_VERSION_CONFLICT') { await detail.refetch(); toast.error('Task đã thay đổi ở nơi khác. Bản nháp được giữ để bạn đối chiếu.'); } else toast.error(safeMessage(error)); } });
  const checklist = useMutation({ mutationFn: ({ itemKey, checked }: { itemKey: string; checked: boolean }) => { if (!task) throw new Error('Task chưa sẵn sàng'); return setPublicationChecklist(task, itemKey, checked ? 'COMPLETED' : 'PENDING'); }, onSuccess: (updated) => void sync(updated, 'Đã cập nhật checklist.'), onError: (error) => toast.error(safeMessage(error)) });
  const download = useMutation({ mutationFn: (role: 'VIDEO'|'SUBTITLE'|'THUMBNAIL') => requestPublicationDownload(task!.id, role), onSuccess: (grant) => { window.open(grant.url, '_blank', 'noopener,noreferrer'); }, onError: (error) => toast.error(safeMessage(error)) });
  const close = () => draftDirty ? setDiscardOpen(true) : onClose();

  return <><Sheet open={Boolean(id)} onOpenChange={(open) => { if (!open) close(); }}><SheetContent className="publishing-sheet overflow-y-auto sm:max-w-2xl" onEscapeKeyDown={(event) => { if (draftDirty) { event.preventDefault(); setDiscardOpen(true); } }}><SheetHeader><SheetTitle>{task ? task.destinationName : 'Publication task'}</SheetTitle><SheetDescription>{task ? `${task.platform} · video ${shortId(task.videoId)} · package ${shortId(task.packageId)}` : 'Đang tải nội dung task…'}</SheetDescription></SheetHeader>{detail.isPending ? <ListState state="loading" title="Đang tải task" description="Đang lấy metadata, checklist và proof mới nhất…" /> : detail.isError || !task ? <ListState state="error" title="Không thể tải task" description={safeMessage(detail.error)} action={<Button onClick={() => void detail.refetch()}>Thử lại</Button>} /> : <div className="publishing-detail"><div className="publishing-detail-status"><TaskStatus value={task.status} /><Badge variant="outline">Version {task.version}</Badge>{draftDirty && <Badge variant="outline" className="publishing-unsaved">Chưa lưu</Badge>}</div><AssetPanel task={task} pending={download.isPending} onDownload={(role) => download.mutate(role)} /><PlanPanel task={task} scheduledAt={scheduledAt} deadlineAt={deadlineAt} notes={notes} pending={action.isPending} onScheduledAt={setScheduledAt} onDeadlineAt={setDeadlineAt} onNotes={setNotes} onSave={() => action.mutate({ kind: 'plan' })} /><FieldsPanel task={task} values={fields} pending={action.isPending} onChange={(key, value) => setFields((current) => ({ ...current, [key]: value }))} onSave={(fieldKey) => action.mutate({ kind: 'field', fieldKey })} onLock={(fieldKey) => action.mutate({ kind: 'lock', fieldKey })} /><ChecklistPanel task={task} pending={checklist.isPending} onChange={(itemKey, checked) => checklist.mutate({ itemKey, checked })} /><ProofPanel task={task} url={proofUrl} postId={postId} pending={action.isPending} onUrl={setProofUrl} onPostId={setPostId} onSubmit={() => action.mutate({ kind: 'proof' })} onVerify={(proofId, success) => action.mutate({ kind: success ? 'verify' : 'fail-proof', proofId })} /></div>} {task && <SheetFooter className="publishing-sheet-footer"><PublicationActions task={task} pending={action.isPending} onAction={(kind) => action.mutate({ kind })} /></SheetFooter>}</SheetContent></Sheet><AlertDialog open={discardOpen} onOpenChange={setDiscardOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Bỏ thay đổi chưa lưu?</AlertDialogTitle><AlertDialogDescription>Metadata hoặc lịch đăng đang có thay đổi cục bộ. Đóng task sẽ bỏ những thay đổi này.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Tiếp tục chỉnh sửa</AlertDialogCancel><AlertDialogAction onClick={() => { setDiscardOpen(false); loadedRef.current = null; onClose(); }}>Bỏ thay đổi</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

function AssetPanel({ task, pending, onDownload }: { task: PublicationTask; pending: boolean; onDownload: (role: 'VIDEO'|'SUBTITLE'|'THUMBNAIL') => void }) { return <Card><CardHeader><CardTitle>Asset bàn giao</CardTitle><CardDescription>Link tải là presigned grant ngắn hạn; storage identity không xuất hiện trong task.</CardDescription></CardHeader><CardContent className="publishing-assets">{(['VIDEO','SUBTITLE','THUMBNAIL'] as const).map((role) => <Button key={role} variant="outline" disabled={!task.assetAvailability[role] || pending} onClick={() => onDownload(role)}><DownloadIcon />{assetLabel(role)}</Button>)}</CardContent></Card>; }
function PlanPanel({ task, scheduledAt, deadlineAt, notes, pending, onScheduledAt, onDeadlineAt, onNotes, onSave }: { task: PublicationTask; scheduledAt: string; deadlineAt: string; notes: string; pending: boolean; onScheduledAt: (value: string) => void; onDeadlineAt: (value: string) => void; onNotes: (value: string) => void; onSave: () => void }) { return <Card><CardHeader><CardTitle>Kế hoạch đăng</CardTitle><CardDescription>Lịch là dữ liệu điều phối, không tự đăng lên nền tảng.</CardDescription></CardHeader><CardContent className="publishing-plan"><label><span>Thời gian dự kiến</span><Input type="datetime-local" value={scheduledAt} onChange={(event) => onScheduledAt(event.target.value)} /></label><label><span>Deadline</span><Input type="datetime-local" value={deadlineAt} onChange={(event) => onDeadlineAt(event.target.value)} /></label><label className="publishing-plan-notes"><span>Ghi chú</span><Textarea value={notes} maxLength={2000} onChange={(event) => onNotes(event.target.value)} placeholder="Lưu ý khi đăng thủ công…" /></label><Button variant="outline" disabled={pending || ['VERIFIED','CANCELLED'].includes(task.status)} onClick={onSave}>Lưu kế hoạch</Button></CardContent></Card>; }
function FieldsPanel({ task, values, pending, onChange, onSave, onLock }: { task: PublicationTask; values: Record<string,string>; pending: boolean; onChange: (key: string, value: string) => void; onSave: (key: string) => void; onLock: (key: string) => void }) { return <Card><CardHeader><CardTitle>Metadata</CardTitle><CardDescription>Mỗi lần lưu tạo revision mới. Chỉnh content sau duyệt sẽ làm approval cũ stale.</CardDescription></CardHeader><CardContent className="publishing-fields">{task.fields.map((field) => <div key={field.id} className="publishing-field"><div><label htmlFor={`field-${field.id}`}>{fieldLabel(field.key)}</label><span>Revision {field.currentRevision?.revision ?? 0} · {field.isLocked ? 'Đã khóa' : 'Có thể chỉnh sửa'}</span></div><Textarea id={`field-${field.id}`} value={values[field.key] ?? ''} disabled={field.isLocked || ['PUBLISHED','VERIFIED','CANCELLED'].includes(task.status)} onChange={(event) => onChange(field.key, event.target.value)} /><div><Button size="sm" variant="outline" disabled={!values[field.key] || pending} onClick={() => void copyText(values[field.key] ?? '')}><ClipboardIcon />Sao chép</Button><Button size="sm" variant="outline" disabled={pending || ['PUBLISHED','VERIFIED','CANCELLED'].includes(task.status)} onClick={() => onLock(field.key)}>{field.isLocked ? <UnlockIcon /> : <LockIcon />}{field.isLocked ? 'Mở khóa' : 'Khóa'}</Button><Button size="sm" disabled={field.isLocked || pending || (values[field.key] ?? '') === (field.currentRevision?.value ?? '')} onClick={() => onSave(field.key)}>Lưu field</Button></div></div>)}</CardContent></Card>; }
function ChecklistPanel({ task, pending, onChange }: { task: PublicationTask; pending: boolean; onChange: (key: string, checked: boolean) => void }) { return <Card><CardHeader><CardTitle>Checklist đăng thủ công</CardTitle><CardDescription>Task chỉ nhận proof khi mọi mục bắt buộc đã hoàn tất.</CardDescription></CardHeader><CardContent className="publishing-checklist">{task.checklist.map((item) => <label key={item.id}><Checkbox checked={item.status === 'COMPLETED'} disabled={pending || ['VERIFIED','CANCELLED'].includes(task.status)} onCheckedChange={(checked) => onChange(item.key, checked === true)} /><span><strong>{item.label}</strong><small>{item.isRequired ? 'Bắt buộc' : 'Tùy chọn'} · {item.status === 'COMPLETED' ? 'Đã xong' : 'Chưa xong'}</small></span></label>)}</CardContent></Card>; }
function ProofPanel({ task, url, postId, pending, onUrl, onPostId, onSubmit, onVerify }: { task: PublicationTask; url: string; postId: string; pending: boolean; onUrl: (value: string) => void; onPostId: (value: string) => void; onSubmit: () => void; onVerify: (id: string, success: boolean) => void }) { const canSubmit = ['POSTING_MANUAL','PUBLISHED'].includes(task.status); return <Card><CardHeader><CardTitle>Publication proof</CardTitle><CardDescription>Mỗi lần gửi là một attempt mới; lịch sử cũ không bị ghi đè.</CardDescription></CardHeader><CardContent className="publishing-proof"><div className="publishing-proof-form"><label><span>Public URL</span><Input type="url" value={url} disabled={!canSubmit} onChange={(event) => onUrl(event.target.value)} placeholder="https://…" /></label><label><span>Platform post ID</span><Input value={postId} disabled={!canSubmit} onChange={(event) => onPostId(event.target.value)} placeholder="ID bài đăng" /></label><Button disabled={!canSubmit || pending || (!url.trim() && !postId.trim())} onClick={onSubmit}><SendIcon />Ghi nhận proof</Button></div>{task.proofs.length ? <div className="publishing-proof-list">{task.proofs.map((proof, index) => <article key={proof.id}><div><strong>Lần {proof.attemptNumber}</strong><ProofStatus value={proof.verificationStatus} /></div><p>{proof.publicUrl ? <a href={proof.publicUrl} target="_blank" rel="noreferrer">{proof.publicUrl}<ExternalLinkIcon /></a> : proof.platformPostId}</p><time>{formatDate(proof.submittedAt)}</time>{index === 0 && proof.verificationStatus === 'PENDING' && <div><Button size="sm" variant="outline" disabled={pending} onClick={() => onVerify(proof.id, false)}>Đánh dấu lỗi</Button><Button size="sm" disabled={pending} onClick={() => onVerify(proof.id, true)}><CheckIcon />Xác minh</Button></div>}</article>)}</div> : <p className="publishing-muted">Chưa có proof attempt.</p>}</CardContent></Card>; }
function PublicationActions({ task, pending, onAction }: { task: PublicationTask; pending: boolean; onAction: (kind: string) => void }) { if (task.status === 'CONTENT_GENERATED' || task.status === 'NEEDS_REVISION') return <Button disabled={pending} onClick={() => onAction('approve')}><CheckIcon />Duyệt nội dung</Button>; if (task.status === 'READY_TO_PUBLISH') return <Button disabled={pending} onClick={() => onAction('start')}><SendIcon />Bắt đầu đăng thủ công</Button>; if (['CONTENT_APPROVED','POSTING_MANUAL','PUBLISHED','VERIFIED'].includes(task.status)) return <Button variant="outline" disabled={pending} onClick={() => onAction('revision')}><RotateCcwIcon />Yêu cầu chỉnh sửa</Button>; return <span className="publishing-muted">Hoàn thiện metadata để tiếp tục.</span>; }

function TaskStatus({ value }: { value: PublicationTaskStatus }) { return <Badge variant="outline" className={`publishing-status tone-${statusTone(value)}`}>{statusLabel(value)}</Badge>; }
function ProofStatus({ value }: { value: 'PENDING'|'VERIFIED'|'FAILED' }) { return <Badge variant="outline" className={`publishing-status tone-${value === 'VERIFIED' ? 'done' : value === 'FAILED' ? 'failed' : 'waiting'}`}>{value === 'VERIFIED' ? 'Đã xác minh' : value === 'FAILED' ? 'Thất bại' : 'Chờ xác minh'}</Badge>; }
function statusSummary(tasks: PublicationTaskItem[]) { return STATUSES.map((status) => ({ status, count: tasks.filter((task) => task.status === status).length })).filter((item) => item.count); }
function statusLabel(value: PublicationTaskStatus) { return ({ READY_FOR_CONTENT: 'Chờ nội dung', CONTENT_GENERATED: 'Đã có nội dung', CONTENT_APPROVED: 'Đã duyệt nội dung', READY_TO_PUBLISH: 'Sẵn sàng đăng', POSTING_MANUAL: 'Đang đăng thủ công', PUBLISHED: 'Đã đăng', VERIFIED: 'Đã xác minh', NEEDS_REVISION: 'Cần chỉnh sửa', CANCELLED: 'Đã hủy' } as const)[value]; }
function statusTone(value: PublicationTaskStatus) { if (value === 'VERIFIED') return 'done'; if (value === 'CANCELLED') return 'cancelled'; if (value === 'NEEDS_REVISION') return 'failed'; if (value === 'READY_FOR_CONTENT') return 'waiting'; if (value === 'CONTENT_GENERATED' || value === 'CONTENT_APPROVED') return 'review'; if (value === 'READY_TO_PUBLISH') return 'ready'; if (value === 'POSTING_MANUAL') return 'running'; return 'published'; }
function assetLabel(value: string) { return ({ VIDEO: 'Tải video', SUBTITLE: 'Tải SRT', THUMBNAIL: 'Tải thumbnail' } as Record<string,string>)[value] ?? value; }
function fieldLabel(value: string) { return ({ title: 'Tiêu đề', description: 'Mô tả', keywords: 'Từ khóa', hashtags: 'Hashtags', thumbnailText: 'Chữ thumbnail', thumbnailPrompt: 'Prompt thumbnail', caption: 'Caption' } as Record<string,string>)[value] ?? value; }
function actionMessage(kind: string) { return ({ field: 'Đã tạo revision metadata mới.', lock: 'Đã cập nhật khóa field.', plan: 'Đã lưu kế hoạch đăng.', approve: 'Đã duyệt nội dung.', start: 'Đã bắt đầu đăng thủ công.', proof: 'Đã ghi nhận proof attempt.', verify: 'Đã xác minh proof.', 'fail-proof': 'Đã ghi nhận proof thất bại.', revision: 'Đã mở vòng chỉnh sửa mới.' } as Record<string,string>)[kind] ?? 'Đã cập nhật task.'; }
function shortId(value: string) { return value.slice(0, 8).toUpperCase(); }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(value)) : '—'; }
function formatTime(value: string) { return new Intl.DateTimeFormat('vi-VN', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(value)); }
function formatDay(value: string) { return new Intl.DateTimeFormat('vi-VN', { weekday: 'long', day: '2-digit', month: '2-digit', year: 'numeric', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(`${value}T00:00:00+07:00`)); }
function localDate(value: string) { return new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(value)); }
function groupByDate(tasks: PublicationTaskItem[]): Array<[string, PublicationTaskItem[]]> { const map = new Map<string, PublicationTaskItem[]>(); tasks.forEach((task) => { const key = task.scheduledAt ? localDate(task.scheduledAt) : 'unscheduled'; map.set(key, [...(map.get(key) ?? []), task]); }); return [...map.entries()].sort(([a], [b]) => a === 'unscheduled' ? 1 : b === 'unscheduled' ? -1 : a.localeCompare(b)); }
function isOverdue(task: PublicationTaskItem) { return Boolean(task.deadlineAt && new Date(task.deadlineAt) < new Date() && !['PUBLISHED','VERIFIED','CANCELLED'].includes(task.status)); }
function toLocalInput(value: string | null) { if (!value) return ''; const date = new Date(value); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 16); }
async function copyText(value: string) { await navigator.clipboard.writeText(value); toast.success('Đã sao chép metadata.'); }
function safeMessage(error: unknown) { return error instanceof PublishingApiError || error instanceof Error ? error.message : 'Không thể hoàn tất thao tác Publishing.'; }
