import { Body, Controller, Headers, HttpCode, Inject, Param, Post } from '@nestjs/common';
import { ProblemDetailsException } from '../../../../platform/http/problem-details.exception';
import { WorkerTasksService } from '../../application/worker-tasks.service';
import { WorkerError } from '../../domain/worker-errors';
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { ClaimTaskDto, CommitOutputDto, CompleteTaskDto, FailTaskDto, LeaseActionDto, OutputGrantDto, TaskProgressDto } from './worker-tasks.dto';

@Controller('worker/v1/tasks')
export class WorkerTasksController {
  constructor(@Inject(WorkerTasksService) private readonly tasks: WorkerTasksService) {}
  @Post('claim') @HttpCode(200) claim(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: ClaimTaskDto) { requiredKey(key); return this.run(() => this.tasks.claim(bearer(auth), body.sessionId)); }
  @Post(':taskId/attempts/:attemptId/start') @HttpCode(200) start(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Body() body: LeaseActionDto) { const idem = requiredKey(key); return this.run(() => this.tasks.start(bearer(auth), taskId, attemptId, body, idem)); }
  @Post(':taskId/attempts/:attemptId/renew') @HttpCode(200) renew(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Body() body: LeaseActionDto) { const idem = requiredKey(key); return this.run(() => this.tasks.renew(bearer(auth), taskId, attemptId, body, idem)); }
  @Post(':taskId/attempts/:attemptId/progress') @HttpCode(200) progress(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Body() body: TaskProgressDto) { const idem = requiredKey(key); return this.run(() => this.tasks.progress(bearer(auth), taskId, attemptId, body, idem)); }
  @Post(':taskId/attempts/:attemptId/inputs/:assetId/refresh') @HttpCode(200) input(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Param('assetId') assetId: string, @Body() body: LeaseActionDto) { requiredKey(key); return this.run(() => this.tasks.inputGrant(bearer(auth), taskId, attemptId, assetId, body)); }
  @Post(':taskId/attempts/:attemptId/outputs') output(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Body() body: OutputGrantDto) { requiredKey(key); return this.run(() => this.tasks.createOutput(bearer(auth), taskId, attemptId, body)); }
  @Post(':taskId/attempts/:attemptId/outputs/:assetId/refresh') @HttpCode(200) refreshOutput(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Param('assetId') assetId: string, @Body() body: LeaseActionDto) { requiredKey(key); return this.run(() => this.tasks.refreshOutput(bearer(auth), taskId, attemptId, assetId, body)); }
  @Post(':taskId/attempts/:attemptId/outputs/:assetId/commit') @HttpCode(200) commitOutput(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Param('assetId') assetId: string, @Body() body: CommitOutputDto) { const idem = requiredKey(key); return this.run(() => this.tasks.commitOutput(bearer(auth), taskId, attemptId, assetId, body, idem)); }
  @Post(':taskId/attempts/:attemptId/complete') @HttpCode(200) complete(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Body() body: CompleteTaskDto) { const idem = requiredKey(key); return this.run(() => this.tasks.complete(bearer(auth), taskId, attemptId, body, idem)); }
  @Post(':taskId/attempts/:attemptId/fail') @HttpCode(200) fail(@Headers('authorization') auth: string | undefined, @Headers('idempotency-key') key: string | undefined, @Param('taskId') taskId: string, @Param('attemptId') attemptId: string, @Body() body: FailTaskDto) { const idem = requiredKey(key); return this.run(() => this.tasks.fail(bearer(auth), taskId, attemptId, body, idem)); }
  private async run<T>(action: () => Promise<T>): Promise<T> { try { return await action(); } catch (error) { if (!(error instanceof WorkerError)) throw error; const status = error.code === 'WORKER_CREDENTIAL_REVOKED' ? 401 : error.code === 'WORKER_VALIDATION_FAILED' ? 400 : error.code.endsWith('_NOT_FOUND') ? 404 : 409; throw new ProblemDetailsException(status, publicCode(error.code), error.message); } }
}
function bearer(value?: string) { const match = /^Bearer ([A-Za-z0-9_-]{20,})$/u.exec(value ?? ''); if (!match) throw new ProblemDetailsException(401, 'WORKER_CREDENTIAL_REVOKED', 'Worker credential is invalid'); return match[1]!; }
function requiredKey(value?: string) { if (!value || !/^[\x21-\x7e]{8,128}$/u.test(value)) throw new ProblemDetailsException(400, 'VALIDATION_ERROR', 'Idempotency-Key is required'); return value; }
function publicCode(code: string) { return code === 'WORKER_VALIDATION_FAILED' ? 'VALIDATION_ERROR' : code; }
