import { Type } from 'class-transformer';
import { IsArray, IsIn, IsInt, IsObject, IsOptional, IsString, Matches, Max, MaxLength, Min, ValidateNested } from 'class-validator';
import type { ClaimTaskRequest, CommitOutputRequest, CompleteTaskRequest, FailTaskRequest, LeaseActionRequest, OutputGrantRequest, TaskMetrics, TaskOutputReference, TaskProgressRequest } from '@reup-dubbing-studio/api-contract/worker';

export class ClaimTaskDto implements ClaimTaskRequest { @IsString() sessionId!: string; @IsInt() @Min(0) @Max(25) waitSeconds!: number; }
export class LeaseActionDto implements LeaseActionRequest { @IsString() leaseId!: string; @IsString() @Matches(/^\d+$/u) fencingToken!: string; }
export class TaskProgressDto extends LeaseActionDto implements TaskProgressRequest { @IsInt() @Min(0) @Max(10_000) progressBps!: number; @IsOptional() @IsString() @MaxLength(500) detailSafe?: string | null; }
export class OutputGrantDto extends LeaseActionDto implements OutputGrantRequest { @IsString() @MaxLength(120) slot!: string; @IsString() @MaxLength(255) fileName!: string; @IsString() @MaxLength(160) contentType!: string; @IsString() @Matches(/^\d+$/u) byteSize!: string; @IsString() @Matches(/^[a-f0-9]{64}$/u) checksumSha256!: string; @IsObject() metadata!: Record<string, unknown>; }
export class CommitOutputDto extends LeaseActionDto implements CommitOutputRequest { @IsString() @Matches(/^\d+$/u) byteSize!: string; @IsString() @Matches(/^[a-f0-9]{64}$/u) checksumSha256!: string; }
class TaskOutputReferenceDto implements TaskOutputReference { @IsString() slot!: string; @IsString() assetId!: string; }
class TaskMetricsDto implements TaskMetrics { @IsOptional() @IsInt() @Min(0) downloadMs?: number; @IsOptional() @IsInt() @Min(0) modelLoadMs?: number; @IsOptional() @IsInt() @Min(0) executionMs?: number; @IsOptional() @IsInt() @Min(0) uploadMs?: number; @IsOptional() @IsInt() @Min(0) gpuActiveMs?: number; @IsOptional() @IsInt() @Min(0) peakVramMb?: number; @IsOptional() @IsString() @Matches(/^\d+$/u) inputBytes?: string; @IsOptional() @IsString() @Matches(/^\d+$/u) outputBytes?: string; @IsOptional() @IsInt() exitCode?: number | null; }
export class CompleteTaskDto extends LeaseActionDto implements CompleteTaskRequest { @IsArray() @ValidateNested({ each: true }) @Type(() => TaskOutputReferenceDto) outputs!: TaskOutputReferenceDto[]; @IsObject() result!: Record<string, unknown>; @ValidateNested() @Type(() => TaskMetricsDto) metrics!: TaskMetricsDto; }
const failureCodes = ['MODEL_LOAD_FAILED', 'INFERENCE_FAILED', 'PROCESS_EXITED', 'PROCESS_TIMEOUT', 'DOWNLOAD_FAILED', 'UPLOAD_FAILED', 'CHECKSUM_FAILED', 'INVALID_INPUT', 'OUT_OF_MEMORY', 'SCRATCH_EXHAUSTED', 'TRANSIENT_STORAGE_ERROR', 'TRANSIENT_NETWORK_ERROR'] as const;
export class FailTaskDto extends LeaseActionDto implements FailTaskRequest { @IsIn(failureCodes) code!: FailTaskRequest['code']; @IsString() @MaxLength(500) detailSafe!: string; @ValidateNested() @Type(() => TaskMetricsDto) metrics!: TaskMetricsDto; }
