import type { CreateVoiceProfile, UpdateVoiceProfile, VoiceLicenseKind, VoiceProfile } from '@reup-dubbing-studio/api-client';
export type VoiceDraft = { name: string; primaryLanguage: string; description: string; tags: string; licenseKind: VoiceLicenseKind; licenseReference: string; sourceReference: string; commercialUseAllowed: boolean };
export type VoiceFormErrors = Partial<Record<keyof VoiceDraft, string>>;
export const emptyVoiceDraft = (): VoiceDraft => ({ name: '', primaryLanguage: 'vi', description: '', tags: '', licenseKind: 'OWNED_RECORDING', licenseReference: '', sourceReference: '', commercialUseAllowed: true });
export const voiceDraft = (voice: VoiceProfile): VoiceDraft => ({ name: voice.name, primaryLanguage: voice.primaryLanguage, description: voice.description ?? '', tags: voice.tags.join(', '), licenseKind: voice.licenseKind, licenseReference: voice.licenseReference ?? '', sourceReference: voice.sourceReference ?? '', commercialUseAllowed: voice.commercialUseAllowed });
export function validateVoiceDraft(draft: VoiceDraft): VoiceFormErrors { const errors: VoiceFormErrors = {}; if (!draft.name.trim()) errors.name = 'Nhập tên giọng.'; if (!/^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/u.test(draft.primaryLanguage)) errors.primaryLanguage = 'Dùng mã BCP 47, ví dụ vi hoặc en-US.'; if (draft.commercialUseAllowed && (draft.licenseKind === 'CC_BY_NC' || draft.licenseKind === 'UNKNOWN')) errors.commercialUseAllowed = 'Loại license này không cho phép sử dụng thương mại.'; if (draft.commercialUseAllowed && draft.licenseKind !== 'OWNED_RECORDING' && !draft.licenseReference.trim()) errors.licenseReference = 'Cần bằng chứng license khi dùng thương mại.'; return errors; }
export function buildVoiceCreate(draft: VoiceDraft): CreateVoiceProfile { return { ...fields(draft), description: nullable(draft.description), licenseReference: nullable(draft.licenseReference), sourceReference: nullable(draft.sourceReference) }; }
export function buildVoiceUpdate(draft: VoiceDraft): UpdateVoiceProfile { return buildVoiceCreate(draft); }
function fields(draft: VoiceDraft) { return { name: draft.name.trim(), primaryLanguage: draft.primaryLanguage.trim(), tags: [...new Set(draft.tags.split(',').map((tag) => tag.trim().toLocaleLowerCase('vi')).filter(Boolean))], licenseKind: draft.licenseKind, commercialUseAllowed: draft.commercialUseAllowed }; }
function nullable(value: string) { return value.trim() || null; }
