// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from '@hey-api/client-fetch';

import { client } from './client.gen.js';
import type { ClaimWorkerTaskData, ClaimWorkerTaskErrors, ClaimWorkerTaskResponses, CommitWorkerTaskOutputData, CommitWorkerTaskOutputErrors, CommitWorkerTaskOutputResponses, CompleteWorkerTaskAttemptData, CompleteWorkerTaskAttemptErrors, CompleteWorkerTaskAttemptResponses, EnrollWorkerData, EnrollWorkerErrors, EnrollWorkerResponses, FailWorkerTaskAttemptData, FailWorkerTaskAttemptErrors, FailWorkerTaskAttemptResponses, HeartbeatWorkerSessionData, HeartbeatWorkerSessionErrors, HeartbeatWorkerSessionResponses, RefreshWorkerTaskInputGrantData, RefreshWorkerTaskInputGrantErrors, RefreshWorkerTaskInputGrantResponses, RefreshWorkerTaskOutputGrantData, RefreshWorkerTaskOutputGrantErrors, RefreshWorkerTaskOutputGrantResponses, RenewWorkerTaskLeaseData, RenewWorkerTaskLeaseErrors, RenewWorkerTaskLeaseResponses, ReportWorkerTaskProgressData, ReportWorkerTaskProgressErrors, ReportWorkerTaskProgressResponses, RequestWorkerTaskOutputGrantData, RequestWorkerTaskOutputGrantErrors, RequestWorkerTaskOutputGrantResponses, StartWorkerSessionData, StartWorkerSessionErrors, StartWorkerSessionResponses, StartWorkerTaskAttemptData, StartWorkerTaskAttemptErrors, StartWorkerTaskAttemptResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Exchange an enrollment token for a scoped credential and first session
 */
export const enrollWorker = <ThrowOnError extends boolean = false>(options: Options<EnrollWorkerData, ThrowOnError>) => {
    return (options.client ?? client).post<EnrollWorkerResponses, EnrollWorkerErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/enroll',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Start a runtime session with an existing Worker credential
 */
export const startWorkerSession = <ThrowOnError extends boolean = false>(options: Options<StartWorkerSessionData, ThrowOnError>) => {
    return (options.client ?? client).post<StartWorkerSessionResponses, StartWorkerSessionErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update capacity and receive drain or cancellation signals
 */
export const heartbeatWorkerSession = <ThrowOnError extends boolean = false>(options: Options<HeartbeatWorkerSessionData, ThrowOnError>) => {
    return (options.client ?? client).post<HeartbeatWorkerSessionResponses, HeartbeatWorkerSessionErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sessions/{sessionId}/heartbeat',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Atomically claim the next eligible GPU task
 */
export const claimWorkerTask = <ThrowOnError extends boolean = false>(options: Options<ClaimWorkerTaskData, ThrowOnError>) => {
    return (options.client ?? client).post<ClaimWorkerTaskResponses, ClaimWorkerTaskErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/claim',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Mark a claimed task attempt as running
 */
export const startWorkerTaskAttempt = <ThrowOnError extends boolean = false>(options: Options<StartWorkerTaskAttemptData, ThrowOnError>) => {
    return (options.client ?? client).post<StartWorkerTaskAttemptResponses, StartWorkerTaskAttemptErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/start',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Renew the current task lease using server time
 */
export const renewWorkerTaskLease = <ThrowOnError extends boolean = false>(options: Options<RenewWorkerTaskLeaseData, ThrowOnError>) => {
    return (options.client ?? client).post<RenewWorkerTaskLeaseResponses, RenewWorkerTaskLeaseErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/renew',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Report monotonic progress for the current task attempt
 */
export const reportWorkerTaskProgress = <ThrowOnError extends boolean = false>(options: Options<ReportWorkerTaskProgressData, ThrowOnError>) => {
    return (options.client ?? client).post<ReportWorkerTaskProgressResponses, ReportWorkerTaskProgressErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/progress',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Refresh a download grant for an authorized task input
 */
export const refreshWorkerTaskInputGrant = <ThrowOnError extends boolean = false>(options: Options<RefreshWorkerTaskInputGrantData, ThrowOnError>) => {
    return (options.client ?? client).post<RefreshWorkerTaskInputGrantResponses, RefreshWorkerTaskInputGrantErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/inputs/{assetId}/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create a pending output asset and upload grant for a declared slot
 */
export const requestWorkerTaskOutputGrant = <ThrowOnError extends boolean = false>(options: Options<RequestWorkerTaskOutputGrantData, ThrowOnError>) => {
    return (options.client ?? client).post<RequestWorkerTaskOutputGrantResponses, RequestWorkerTaskOutputGrantErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/outputs',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Refresh an upload grant for an existing pending output asset
 */
export const refreshWorkerTaskOutputGrant = <ThrowOnError extends boolean = false>(options: Options<RefreshWorkerTaskOutputGrantData, ThrowOnError>) => {
    return (options.client ?? client).post<RefreshWorkerTaskOutputGrantResponses, RefreshWorkerTaskOutputGrantErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/outputs/{assetId}/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Verify an uploaded task output and mark the asset available
 */
export const commitWorkerTaskOutput = <ThrowOnError extends boolean = false>(options: Options<CommitWorkerTaskOutputData, ThrowOnError>) => {
    return (options.client ?? client).post<CommitWorkerTaskOutputResponses, CommitWorkerTaskOutputErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/outputs/{assetId}/commit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Complete the current attempt after all required outputs are available
 */
export const completeWorkerTaskAttempt = <ThrowOnError extends boolean = false>(options: Options<CompleteWorkerTaskAttemptData, ThrowOnError>) => {
    return (options.client ?? client).post<CompleteWorkerTaskAttemptResponses, CompleteWorkerTaskAttemptErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/complete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Fail the current attempt with a safe allowlisted error
 */
export const failWorkerTaskAttempt = <ThrowOnError extends boolean = false>(options: Options<FailWorkerTaskAttemptData, ThrowOnError>) => {
    return (options.client ?? client).post<FailWorkerTaskAttemptResponses, FailWorkerTaskAttemptErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{taskId}/attempts/{attemptId}/fail',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
