// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000/worker/v1' | (string & {});
};

export type UuidV7 = string;

export type FencingToken = string;

export type WorkerRole = 'BATCH_MEDIA' | 'INTERACTIVE_TTS';

export type WorkerDesiredStatus = 'ACTIVE' | 'DRAINING' | 'REVOKED';

export type WorkerTaskType = 'DESUB' | 'TRANSCRIBE_ASR' | 'GENERATE_INITIAL_TTS' | 'REGENERATE_SEGMENT' | 'SEPARATE_AUDIO' | 'RENDER';

export type WorkerResourceClass = 'GPU_BATCH' | 'GPU_TTS_INTERACTIVE';

export type WorkerTaskStatus = 'LEASED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'CANCELLED';

export type AssetKind = 'RAW' | 'DESUBBED' | 'ASR_JSON' | 'BACKGROUND_AUDIO' | 'DUB_AUDIO' | 'VOICE_SAMPLE' | 'VOICE_PROMPT' | 'INTRO' | 'OUTRO' | 'LOGO' | 'WATERMARK' | 'OUTPUT_VIDEO';

export type RenderOutputVariant = 'FULL_16X9' | 'HIGHLIGHT_9X16';

export type SessionIdentity = {
    sessionNonce: UuidV7;
    role: WorkerRole;
    imageDigest: string;
    agentVersion: string;
    contractVersion: number;
    capabilities: Array<string>;
    gpuInventory: Array<{
        [key: string]: unknown;
    }>;
    cpuInventory: {
        [key: string]: unknown;
    };
    capacity: WorkerCapacity;
};

export type WorkerCapacity = {
    maxConcurrentTasks: number;
    availableTaskSlots: number;
    scratchFreeBytes: string;
    vramFreeMb?: number;
};

export type WorkerTelemetry = {
    gpuUtilizationPercent?: number;
    vramUsedMb?: number;
    cpuUtilizationPercent?: number;
    memoryUsedMb?: number;
};

export type Heartbeat = {
    sequence: string;
    sentAt: string;
    capacity: WorkerCapacity;
    currentTaskCount: number;
    activeLeaseIds: Array<UuidV7>;
    telemetry: WorkerTelemetry;
    agentVersion: string;
    contractVersion: number;
};

export type WorkerSession = {
    id: UuidV7;
    sessionNonce: UuidV7;
    imageDigest: string;
    agentVersion: string;
    contractVersion: number;
    capabilities: Array<string>;
    capacity: WorkerCapacity;
    currentTaskCount: number;
    lastHeartbeatSequence: string;
    startedAt: string;
    lastHeartbeatAt: string;
};

export type ClaimTaskRequest = {
    sessionId: UuidV7;
    waitSeconds: number;
};

export type ExecutionRequirements = {
    resourceClass: WorkerResourceClass;
    requiredCapabilities: Array<string>;
    minimumVramMb?: number | null;
    minimumScratchBytes?: string | null;
    expectedRuntimeSeconds?: number | null;
};

export type DownloadGrant = {
    assetId: UuidV7;
    method: 'GET';
    url: string;
    headers: {
        [key: string]: string;
    };
    expiresAt: string;
    fileName: string;
    contentType: string;
    byteSize: string;
    checksumSha256: string | null;
};

export type TaskInputAsset = {
    slot: string;
    kind: AssetKind;
    assetId: UuidV7;
    metadata: {
        [key: string]: unknown;
    };
    download: DownloadGrant;
};

export type TaskOutputSpecification = {
    slot: string;
    kind: AssetKind;
    minItems: number;
    maxItems: number;
    allowedContentTypes: Array<string>;
    maxByteSize: string;
};

export type NormalizedMask = {
    x: number;
    y: number;
    width: number;
    height: number;
};

export type DesubTaskConfiguration = {
    kind: 'DESUB';
    mask: NormalizedMask;
    modelProfile: string;
};

export type AsrTaskConfiguration = {
    kind: 'TRANSCRIBE_ASR';
    language: string;
    modelSize: 'small' | 'medium' | 'large-v3';
};

export type TtsSegment = {
    segmentRevisionId: UuidV7;
    text: string;
    languageId: string;
    voiceProfileId: UuidV7;
    targetDurationMs: number;
    outputSlot: string;
};

export type InitialTtsTaskConfiguration = {
    kind: 'GENERATE_INITIAL_TTS';
    speed: number;
    timingPolicy: 'PRESERVE_SEGMENT' | 'FIT_SEGMENT' | 'ALLOW_DRIFT';
    segments: Array<TtsSegment>;
};

export type RegenerateTtsTaskConfiguration = {
    kind: 'REGENERATE_SEGMENT';
    speed: number;
    timingPolicy: 'PRESERVE_SEGMENT' | 'FIT_SEGMENT' | 'ALLOW_DRIFT';
    segment: TtsSegment;
};

export type SeparateAudioTaskConfiguration = {
    kind: 'SEPARATE_AUDIO';
    modelName: 'htdemucs';
};

export type RenderVariant = {
    variant: RenderOutputVariant;
    outputSlot: string;
    sourceStartMs?: number | null;
    sourceEndMs?: number | null;
};

export type RenderTaskConfiguration = {
    kind: 'RENDER';
    subtitleMode: 'EXTERNAL_ONLY';
    variants: Array<RenderVariant>;
};

export type TaskConfiguration = DesubTaskConfiguration | AsrTaskConfiguration | InitialTtsTaskConfiguration | RegenerateTtsTaskConfiguration | SeparateAudioTaskConfiguration | RenderTaskConfiguration;

export type ClaimedTask = {
    taskId: UuidV7;
    attemptId: UuidV7;
    leaseId: UuidV7;
    fencingToken: FencingToken;
    taskType: WorkerTaskType;
    payloadVersion: 1;
    leaseExpiresAt: string;
    renewAfterSeconds: number;
    requirements: ExecutionRequirements;
    configuration: TaskConfiguration;
    inputs: Array<TaskInputAsset>;
    outputs: Array<TaskOutputSpecification>;
};

export type LeaseActionRequest = {
    leaseId: UuidV7;
    fencingToken: FencingToken;
};

export type TaskProgressRequest = {
    leaseId: UuidV7;
    fencingToken: FencingToken;
    progressBps: number;
    detailSafe?: string | null;
};

export type OutputGrantRequest = {
    leaseId: UuidV7;
    fencingToken: FencingToken;
    slot: string;
    fileName: string;
    contentType: string;
    byteSize: string;
    checksumSha256: string;
    metadata: {
        [key: string]: unknown;
    };
};

export type UploadGrant = {
    assetId: UuidV7;
    slot: string;
    method: 'PUT';
    url: string;
    headers: {
        [key: string]: string;
    };
    expiresAt: string;
    maxByteSize: string;
};

export type CommitOutputRequest = {
    leaseId: UuidV7;
    fencingToken: FencingToken;
    byteSize: string;
    checksumSha256: string;
};

export type CommittedOutput = {
    assetId: UuidV7;
    slot: string;
    status: 'AVAILABLE';
    contentType: string;
    byteSize: string;
    checksumSha256: string;
};

export type TaskOutputReference = {
    slot: string;
    assetId: UuidV7;
};

export type TaskMetrics = {
    downloadMs?: number;
    modelLoadMs?: number;
    executionMs?: number;
    uploadMs?: number;
    gpuActiveMs?: number;
    peakVramMb?: number;
    inputBytes?: string;
    outputBytes?: string;
    exitCode?: number | null;
};

export type CompleteTaskRequest = {
    leaseId: UuidV7;
    fencingToken: FencingToken;
    outputs: Array<TaskOutputReference>;
    result: {
        [key: string]: unknown;
    };
    metrics: TaskMetrics;
};

export type WorkerFailureCode = 'MODEL_LOAD_FAILED' | 'INFERENCE_FAILED' | 'PROCESS_EXITED' | 'PROCESS_TIMEOUT' | 'DOWNLOAD_FAILED' | 'UPLOAD_FAILED' | 'CHECKSUM_FAILED' | 'INVALID_INPUT' | 'OUT_OF_MEMORY' | 'SCRATCH_EXHAUSTED' | 'TRANSIENT_STORAGE_ERROR' | 'TRANSIENT_NETWORK_ERROR';

export type FailTaskRequest = {
    leaseId: UuidV7;
    fencingToken: FencingToken;
    code: WorkerFailureCode;
    detailSafe: string;
    metrics: TaskMetrics;
};

export type Meta = {
    requestId: UuidV7;
};

export type EnrollmentEnvelope = {
    data: {
        credential: string;
        session: WorkerSession;
        heartbeatIntervalSeconds: number;
        offlineTimeoutSeconds: number;
    };
    meta: Meta;
};

export type SessionEnvelope = {
    data: {
        session: WorkerSession;
        desiredStatus: WorkerDesiredStatus;
        heartbeatIntervalSeconds: number;
        offlineTimeoutSeconds: number;
    };
    meta: Meta;
};

export type HeartbeatEnvelope = {
    data: {
        acceptedSequence: string;
        workerId: UuidV7;
        sessionId: UuidV7;
        desiredStatus: WorkerDesiredStatus;
        cancelLeaseIds: Array<UuidV7>;
    };
    meta: Meta;
};

export type ClaimTaskEnvelope = {
    data: {
        task: ClaimedTask | null;
        retryAfterSeconds: number;
        desiredStatus: WorkerDesiredStatus;
    };
    meta: Meta;
};

export type TaskActionEnvelope = {
    data: {
        taskId: UuidV7;
        attemptId: UuidV7;
        leaseId: UuidV7;
        taskStatus: WorkerTaskStatus;
        leaseExpiresAt: string | null;
        cancelRequested: boolean;
        desiredStatus: WorkerDesiredStatus;
    };
    meta: Meta;
};

export type DownloadGrantEnvelope = {
    data: DownloadGrant;
    meta: Meta;
};

export type UploadGrantEnvelope = {
    data: UploadGrant;
    meta: Meta;
};

export type CommittedOutputEnvelope = {
    data: CommittedOutput;
    meta: Meta;
};

export type WorkerProblemCode = 'VALIDATION_ERROR' | 'RATE_LIMITED' | 'INTERNAL_ERROR' | 'IDEMPOTENCY_KEY_REUSED' | 'WORKER_NOT_FOUND' | 'WORKER_NOT_ACTIVE' | 'WORKER_DRAINING' | 'WORKER_SESSION_CONFLICT' | 'WORKER_SESSION_NOT_CURRENT' | 'WORKER_VERSION_MISMATCH' | 'WORKER_IMAGE_NOT_APPROVED' | 'WORKER_HARDWARE_MISMATCH' | 'WORKER_CAPABILITY_MISMATCH' | 'ENROLLMENT_TOKEN_INVALID' | 'ENROLLMENT_TOKEN_EXPIRED' | 'ENROLLMENT_TOKEN_CONSUMED' | 'WORKER_CREDENTIAL_REVOKED' | 'TASK_NOT_FOUND' | 'TASK_NOT_CLAIMABLE' | 'TASK_CAPABILITY_MISMATCH' | 'TASK_LEASE_EXPIRED' | 'STALE_TASK_ATTEMPT' | 'TASK_CANCELLED' | 'TASK_PROGRESS_REGRESSION' | 'TASK_OUTPUT_INVALID' | 'ASSET_NOT_FOUND' | 'ASSET_GRANT_EXPIRED' | 'ASSET_CHECKSUM_MISMATCH' | 'ASSET_NOT_AVAILABLE' | 'ASSET_NOT_OWNED_BY_ATTEMPT';

export type ProblemDetails = {
    type: string;
    title: string;
    status: number;
    detail?: string;
    code: WorkerProblemCode;
    requestId: UuidV7;
};

export type SessionId = UuidV7;

export type TaskId = UuidV7;

export type AttemptId = UuidV7;

export type AssetId = UuidV7;

export type IdempotencyKey = string;

export type EnrollWorkerData = {
    body: SessionIdentity;
    path?: never;
    query?: never;
    url: '/enroll';
};

export type EnrollWorkerErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type EnrollWorkerError = EnrollWorkerErrors[keyof EnrollWorkerErrors];

export type EnrollWorkerResponses = {
    /**
     * One-time credential and runtime session.
     */
    201: EnrollmentEnvelope;
};

export type EnrollWorkerResponse = EnrollWorkerResponses[keyof EnrollWorkerResponses];

export type StartWorkerSessionData = {
    body: SessionIdentity;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/sessions';
};

export type StartWorkerSessionErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type StartWorkerSessionError = StartWorkerSessionErrors[keyof StartWorkerSessionErrors];

export type StartWorkerSessionResponses = {
    /**
     * Runtime session.
     */
    201: SessionEnvelope;
};

export type StartWorkerSessionResponse = StartWorkerSessionResponses[keyof StartWorkerSessionResponses];

export type HeartbeatWorkerSessionData = {
    body: Heartbeat;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        sessionId: UuidV7;
    };
    query?: never;
    url: '/sessions/{sessionId}/heartbeat';
};

export type HeartbeatWorkerSessionErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type HeartbeatWorkerSessionError = HeartbeatWorkerSessionErrors[keyof HeartbeatWorkerSessionErrors];

export type HeartbeatWorkerSessionResponses = {
    /**
     * Accepted heartbeat sequence and current control signals.
     */
    200: HeartbeatEnvelope;
};

export type HeartbeatWorkerSessionResponse = HeartbeatWorkerSessionResponses[keyof HeartbeatWorkerSessionResponses];

export type ClaimWorkerTaskData = {
    body: ClaimTaskRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/tasks/claim';
};

export type ClaimWorkerTaskErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type ClaimWorkerTaskError = ClaimWorkerTaskErrors[keyof ClaimWorkerTaskErrors];

export type ClaimWorkerTaskResponses = {
    /**
     * Claimed task or an explicit empty result.
     */
    200: ClaimTaskEnvelope;
};

export type ClaimWorkerTaskResponse = ClaimWorkerTaskResponses[keyof ClaimWorkerTaskResponses];

export type StartWorkerTaskAttemptData = {
    body: LeaseActionRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/start';
};

export type StartWorkerTaskAttemptErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type StartWorkerTaskAttemptError = StartWorkerTaskAttemptErrors[keyof StartWorkerTaskAttemptErrors];

export type StartWorkerTaskAttemptResponses = {
    /**
     * Current task attempt state.
     */
    200: TaskActionEnvelope;
};

export type StartWorkerTaskAttemptResponse = StartWorkerTaskAttemptResponses[keyof StartWorkerTaskAttemptResponses];

export type RenewWorkerTaskLeaseData = {
    body: LeaseActionRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/renew';
};

export type RenewWorkerTaskLeaseErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type RenewWorkerTaskLeaseError = RenewWorkerTaskLeaseErrors[keyof RenewWorkerTaskLeaseErrors];

export type RenewWorkerTaskLeaseResponses = {
    /**
     * Renewed lease and current control signals.
     */
    200: TaskActionEnvelope;
};

export type RenewWorkerTaskLeaseResponse = RenewWorkerTaskLeaseResponses[keyof RenewWorkerTaskLeaseResponses];

export type ReportWorkerTaskProgressData = {
    body: TaskProgressRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/progress';
};

export type ReportWorkerTaskProgressErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type ReportWorkerTaskProgressError = ReportWorkerTaskProgressErrors[keyof ReportWorkerTaskProgressErrors];

export type ReportWorkerTaskProgressResponses = {
    /**
     * Accepted progress and current control signals.
     */
    200: TaskActionEnvelope;
};

export type ReportWorkerTaskProgressResponse = ReportWorkerTaskProgressResponses[keyof ReportWorkerTaskProgressResponses];

export type RefreshWorkerTaskInputGrantData = {
    body: LeaseActionRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
        assetId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/inputs/{assetId}/refresh';
};

export type RefreshWorkerTaskInputGrantErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type RefreshWorkerTaskInputGrantError = RefreshWorkerTaskInputGrantErrors[keyof RefreshWorkerTaskInputGrantErrors];

export type RefreshWorkerTaskInputGrantResponses = {
    /**
     * Fresh input download grant bounded by the active lease.
     */
    200: DownloadGrantEnvelope;
};

export type RefreshWorkerTaskInputGrantResponse = RefreshWorkerTaskInputGrantResponses[keyof RefreshWorkerTaskInputGrantResponses];

export type RequestWorkerTaskOutputGrantData = {
    body: OutputGrantRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/outputs';
};

export type RequestWorkerTaskOutputGrantErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type RequestWorkerTaskOutputGrantError = RequestWorkerTaskOutputGrantErrors[keyof RequestWorkerTaskOutputGrantErrors];

export type RequestWorkerTaskOutputGrantResponses = {
    /**
     * Pending asset and lease-bounded upload grant.
     */
    201: UploadGrantEnvelope;
};

export type RequestWorkerTaskOutputGrantResponse = RequestWorkerTaskOutputGrantResponses[keyof RequestWorkerTaskOutputGrantResponses];

export type RefreshWorkerTaskOutputGrantData = {
    body: LeaseActionRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
        assetId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/outputs/{assetId}/refresh';
};

export type RefreshWorkerTaskOutputGrantErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type RefreshWorkerTaskOutputGrantError = RefreshWorkerTaskOutputGrantErrors[keyof RefreshWorkerTaskOutputGrantErrors];

export type RefreshWorkerTaskOutputGrantResponses = {
    /**
     * Fresh upload grant for the same pending asset.
     */
    200: UploadGrantEnvelope;
};

export type RefreshWorkerTaskOutputGrantResponse = RefreshWorkerTaskOutputGrantResponses[keyof RefreshWorkerTaskOutputGrantResponses];

export type CommitWorkerTaskOutputData = {
    body: CommitOutputRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
        assetId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/outputs/{assetId}/commit';
};

export type CommitWorkerTaskOutputErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type CommitWorkerTaskOutputError = CommitWorkerTaskOutputErrors[keyof CommitWorkerTaskOutputErrors];

export type CommitWorkerTaskOutputResponses = {
    /**
     * Verified available asset.
     */
    200: CommittedOutputEnvelope;
};

export type CommitWorkerTaskOutputResponse = CommitWorkerTaskOutputResponses[keyof CommitWorkerTaskOutputResponses];

export type CompleteWorkerTaskAttemptData = {
    body: CompleteTaskRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/complete';
};

export type CompleteWorkerTaskAttemptErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type CompleteWorkerTaskAttemptError = CompleteWorkerTaskAttemptErrors[keyof CompleteWorkerTaskAttemptErrors];

export type CompleteWorkerTaskAttemptResponses = {
    /**
     * Terminal successful attempt state.
     */
    200: TaskActionEnvelope;
};

export type CompleteWorkerTaskAttemptResponse = CompleteWorkerTaskAttemptResponses[keyof CompleteWorkerTaskAttemptResponses];

export type FailWorkerTaskAttemptData = {
    body: FailTaskRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        taskId: UuidV7;
        attemptId: UuidV7;
    };
    query?: never;
    url: '/tasks/{taskId}/attempts/{attemptId}/fail';
};

export type FailWorkerTaskAttemptErrors = {
    /**
     * RFC 9457 error without secret detail.
     */
    default: ProblemDetails;
};

export type FailWorkerTaskAttemptError = FailWorkerTaskAttemptErrors[keyof FailWorkerTaskAttemptErrors];

export type FailWorkerTaskAttemptResponses = {
    /**
     * Terminal failed attempt state and retry projection.
     */
    200: TaskActionEnvelope;
};

export type FailWorkerTaskAttemptResponse = FailWorkerTaskAttemptResponses[keyof FailWorkerTaskAttemptResponses];
