import { BadRequestException, Body, Controller, Get, Headers, HttpCode, HttpStatus, Inject, Param, Patch, Post, Query, Res } from '@nestjs/common';
import type { FastifyReply } from 'fastify';
import type { CreatePublicationProof, CreatePublishPackage, PlanPublicationTask, VerifyPublicationProof } from '@reup-dubbing-studio/api-contract';
import { ProblemDetailsException } from '../../../../platform/http/problem-details.exception';
import { PublishingService } from '../../application/publishing.service';
import { PublishingError } from '../../domain/publishing-errors';
import type { PublicationAssetRole, PublicationFilters } from '../../domain/publishing';
// Runtime imports are required for Nest validation metadata.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { CreatePublishPackageDto, PublicationChecklistDto, PublicationFieldDto, PublicationListQueryDto, PublicationLockDto, PublicationPlanDto, PublicationProofDto, PublicationVerificationDto } from './publishing.dto';

@Controller('v1')
export class PublishingController {
  constructor(@Inject(PublishingService) private readonly publishing: PublishingService) {}
  @Get('publication-tasks') list(@Query() query: PublicationListQueryDto) { return this.run(() => this.publishing.list(query as PublicationFilters)); }
  @Post('videos/:videoId/publish-packages') async create(@Param('videoId') videoId: string, @Headers('idempotency-key') key: string | undefined, @Body() body: CreatePublishPackageDto, @Res({ passthrough: true }) response: FastifyReply) { const result = await this.run(() => this.publishing.createPackage(uuid(videoId), body as CreatePublishPackage, idempotencyKey(key))); response.header('ETag', `"${result.version}"`); return result; }
  @Get('publish-packages/:id') async package(@Param('id') id: string, @Res({ passthrough: true }) response: FastifyReply) { const result = await this.run(() => this.publishing.package(uuid(id))); response.header('ETag', `"${result.version}"`); return result; }
  @Get('publication-tasks/:id') async task(@Param('id') id: string, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.task(uuid(id)), response); }
  @Post('publication-tasks/:id/generate-content') @HttpCode(200) generate(@Param('id') id: string, @Headers('if-match') tag: string | undefined, @Headers('idempotency-key') key: string | undefined) { uuid(id); version(tag); idempotencyKey(key); return this.run(() => this.publishing.generate()); }
  @Patch('publication-tasks/:id/fields/:fieldKey') field(@Param('id') id: string, @Param('fieldKey') fieldKey: string, @Headers('if-match') tag: string | undefined, @Body() body: PublicationFieldDto, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.updateField(uuid(id), safeKey(fieldKey), body.value, version(tag)), response); }
  @Post('publication-tasks/:id/fields/:fieldKey/regenerate') @HttpCode(200) regenerate(@Param('id') id: string, @Param('fieldKey') fieldKey: string, @Headers('if-match') tag: string | undefined, @Headers('idempotency-key') key: string | undefined) { uuid(id); safeKey(fieldKey); version(tag); idempotencyKey(key); return this.run(() => this.publishing.regenerate()); }
  @Patch('publication-tasks/:id/fields/:fieldKey/lock') lock(@Param('id') id: string, @Param('fieldKey') fieldKey: string, @Headers('if-match') tag: string | undefined, @Body() body: PublicationLockDto, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.lockField(uuid(id), safeKey(fieldKey), body.isLocked, version(tag)), response); }
  @Post('publication-tasks/:id/approve-content') @HttpCode(200) approve(@Param('id') id: string, @Headers('if-match') tag: string | undefined, @Headers('idempotency-key') key: string | undefined, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.approve(uuid(id), version(tag), idempotencyKey(key)), response); }
  @Patch('publication-tasks/:id/plan') plan(@Param('id') id: string, @Headers('if-match') tag: string | undefined, @Body() body: PublicationPlanDto, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.plan(uuid(id), version(tag), body as PlanPublicationTask), response); }
  @Patch('publication-tasks/:id/checklist/:itemKey') checklist(@Param('id') id: string, @Param('itemKey') itemKey: string, @Headers('if-match') tag: string | undefined, @Body() body: PublicationChecklistDto, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.checklist(uuid(id), safeKey(itemKey), body.status, version(tag)), response); }
  @Post('publication-tasks/:id/start-manual-posting') @HttpCode(200) start(@Param('id') id: string, @Headers('if-match') tag: string | undefined, @Headers('idempotency-key') key: string | undefined, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.start(uuid(id), version(tag), idempotencyKey(key)), response); }
  @Post('publication-tasks/:id/proofs') async proof(@Param('id') id: string, @Headers('if-match') tag: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: PublicationProofDto, @Res({ passthrough: true }) response: FastifyReply) { response.status(HttpStatus.CREATED); return this.withEtag(() => this.publishing.proof(uuid(id), version(tag), body as CreatePublicationProof, idempotencyKey(key)), response); }
  @Post('publication-tasks/:id/proofs/:proofId/verify') @HttpCode(200) verify(@Param('id') id: string, @Param('proofId') proofId: string, @Headers('if-match') tag: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: PublicationVerificationDto, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.verify(uuid(id), uuid(proofId), version(tag), body as VerifyPublicationProof, idempotencyKey(key)), response); }
  @Post('publication-tasks/:id/request-revision') @HttpCode(200) revision(@Param('id') id: string, @Headers('if-match') tag: string | undefined, @Headers('idempotency-key') key: string | undefined, @Res({ passthrough: true }) response: FastifyReply) { return this.withEtag(() => this.publishing.requestRevision(uuid(id), version(tag), idempotencyKey(key)), response); }
  @Post('publication-tasks/:id/assets/:role/download-grant') @HttpCode(200) download(@Param('id') id: string, @Param('role') role: PublicationAssetRole) { if (!['VIDEO','SUBTITLE','THUMBNAIL'].includes(role)) throw new BadRequestException('Asset role is invalid'); return this.run(() => this.publishing.download(uuid(id), role)); }
  private async withEtag<T extends { version: number }>(action: () => Promise<T>, response: FastifyReply) { const result = await this.run(action); response.header('ETag', `"${result.version}"`); return result; }
  private async run<T>(action: () => Promise<T>): Promise<T> { try { return await action(); } catch (error) { if (!(error instanceof PublishingError)) throw error; const status = error.code.endsWith('NOT_FOUND') ? 404 : error.code === 'PUBLICATION_VERSION_CONFLICT' ? 412 : error.code === 'IDEMPOTENCY_KEY_REUSED' ? 409 : error.code === 'PUBLICATION_CONTENT_AGENT_UNAVAILABLE' ? 503 : 422; throw new ProblemDetailsException(status, error.code, error.message); } }
}
function uuid(value: string) { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value)) throw new BadRequestException('ID must be a UUID v7'); return value; }
function version(value: string | undefined) { const match = /^"([1-9]\d*)"$/u.exec(value ?? ''); if (!match) throw new BadRequestException('If-Match must contain a strong publication ETag'); return Number(match[1]); }
function idempotencyKey(value: string | undefined) { if (!value || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value)) throw new BadRequestException('Idempotency-Key must be a UUID'); return value; }
function safeKey(value: string) { if (!/^[a-z][A-Za-z0-9]{0,63}$/u.test(value)) throw new BadRequestException('Field key is invalid'); return value; }
