import { createHash } from 'node:crypto';
import type { Prisma, PrismaClient, WorkerDesiredStatus, WorkerObservedStatus, WorkerRole } from '@prisma/client';
import { Observable } from 'rxjs';
import { uuidV7 } from '../../../platform/ids/uuid-v7';
import type { CreateImageInput, CreateWorkerInput, EnrollmentInput, HeartbeatInput, WorkerFilters } from '../domain/workers';
import { WorkerError } from '../domain/worker-errors';

const TOKEN_TTL_MS = 15 * 60_000;
const OFFLINE_MS = 45_000;
const workerInclude = { approvedImage: true, sessions: { where: { endedAt: null }, include: { taskLeases: { where: { releasedAt: null }, select: { id: true } } }, take: 1, orderBy: { startedAt: 'desc' as const } }, billingSessions: { where: { billingEndedAt: null }, take: 1 } };
type WorkerRow = Prisma.WorkerGetPayload<{ include: typeof workerInclude }>;

export class PrismaWorkersRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async list(filters: WorkerFilters) {
    await this.refreshOffline(); const limit = Math.min(filters.limit ?? 50, 100); const cursor = decodeCursor(filters.cursor);
    const rows = await this.prisma.worker.findMany({ where: {
      ...(filters.role ? { role: filters.role as WorkerRole } : {}), ...(filters.observedStatus ? { observedStatus: filters.observedStatus as WorkerObservedStatus } : {}),
      ...(filters.desiredStatus ? { desiredStatus: filters.desiredStatus as WorkerDesiredStatus } : {}), ...(filters.provider ? { provider: filters.provider } : {}),
      ...(filters.query ? { OR: [{ displayName: { contains: filters.query, mode: 'insensitive' } }, { providerInstanceId: { contains: filters.query, mode: 'insensitive' } }] } : {}),
      ...(cursor ? { OR: [{ createdAt: { lt: cursor.createdAt } }, { createdAt: cursor.createdAt, id: { lt: cursor.id } }] } : {}),
    }, include: workerInclude, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }], take: limit + 1 });
    const page = rows.slice(0, limit); const last = page.at(-1); return { items: page.map(view), nextCursor: rows.length > limit && last ? encodeCursor(last.createdAt, last.id) : null };
  }
  async detail(id: string) { await this.refreshOffline(); return view(await this.row(id)); }
  async images() { const rows = await this.prisma.approvedWorkerImage.findMany({ orderBy: [{ createdAt: 'desc' }, { id: 'desc' }] }); return { items: rows.map(imageView), nextCursor: null }; }
  createImage(input: CreateImageInput, key: string, requestHash: string) { return this.mutate('WORKER_CREATE_IMAGE_V1', key, requestHash, async (tx) => imageView(await tx.approvedWorkerImage.create({ data: { id: uuidV7(), ...input } }))); }
  revokeImage(id: string, version: number, key: string) { return this.mutate('WORKER_REVOKE_IMAGE_V1', key, hash({ id, version }), async (tx) => { const row = await tx.approvedWorkerImage.findUnique({ where: { id } }); if (!row) missing(); if (row.version !== version) conflict(); if (row.status !== 'REVOKED') await tx.approvedWorkerImage.update({ where: { id }, data: { status: 'REVOKED', revokedAt: new Date(), version: { increment: 1 } } }); return imageView((await tx.approvedWorkerImage.findUnique({ where: { id } }))!); }); }
  create(input: CreateWorkerInput, key: string, requestHash: string, token: string, tokenHash: string) {
    const keyHash = hash(key); return this.prisma.$transaction(async (tx) => {
      const old = await tx.idempotencyRecord.findUnique({ where: { scope_key: { scope: 'WORKER_CREATE_V1', key: keyHash } } });
      if (old) { if (old.requestHash !== requestHash) reused(); const saved = old.responseBody as { id: string }; return { worker: view(await this.rowWith(tx, saved.id)), enrollment: { secretAvailable: false, token: null, expiresAt: null } }; }
      const image = await tx.approvedWorkerImage.findUnique({ where: { id: input.approvedImageId } }); if (!image || image.status !== 'ACTIVE' || image.role !== input.role) throw new WorkerError('WORKER_IMAGE_NOT_APPROVED', 'Approved image does not match the worker role');
      const workerId = uuidV7(); const expiresAt = new Date(Date.now() + TOKEN_TTL_MS);
      await tx.worker.create({ data: { id: workerId, displayName: input.displayName.trim(), role: input.role, provider: input.provider.trim(), providerInstanceId: input.providerInstanceId?.trim() || null, expectedGpuModel: input.expectedGpuModel?.trim() || null, expectedVramMb: input.expectedVramMb ?? null, approvedImageId: input.approvedImageId } });
      await tx.workerBillingSession.create({ data: { id: uuidV7(), workerId, provider: input.provider.trim(), providerInstanceId: input.providerInstanceId?.trim() || null, hourlyRateCp: input.hourlyRateCp, paidVndPerCp: input.paidVndPerCp ?? null, billingStartedAt: new Date(input.billingStartedAt) } });
      await tx.workerEnrollmentToken.create({ data: { id: uuidV7(), workerId, tokenPrefix: token.slice(0, 12), tokenHash, expiresAt } });
      const worker = view(await this.rowWith(tx, workerId)); await tx.idempotencyRecord.create({ data: { id: uuidV7(), scope: 'WORKER_CREATE_V1', key: keyHash, requestHash, responseBody: { id: workerId }, responseEtag: '' } }); await this.event(tx, workerId, worker.version, 'WORKER_CREATED');
      return { worker, enrollment: { secretAvailable: true, token, expiresAt: expiresAt.toISOString() } };
    }, { isolationLevel: 'Serializable' });
  }
  issueToken(id: string, version: number, key: string, token: string, tokenHash: string) {
    const scope = 'WORKER_ISSUE_TOKEN_V1'; const keyHash = hash(key); const requestHash = hash({ id, version });
    return this.prisma.$transaction(async (tx) => {
      const old = await tx.idempotencyRecord.findUnique({ where: { scope_key: { scope, key: keyHash } } });
      if (old) { if (old.requestHash !== requestHash) reused(); const saved = old.responseBody as { workerId: string; version: number }; return { ...saved, secretAvailable: false, token: null, expiresAt: null }; }
      const worker = await tx.worker.findUnique({ where: { id } }); if (!worker) missing(); if (worker.version !== version) conflict(); if (worker.desiredStatus !== 'ACTIVE') throw new WorkerError('WORKER_NOT_ACTIVE', 'Worker is not active');
      const now = new Date(); await tx.workerEnrollmentToken.updateMany({ where: { workerId: id, consumedAt: null, revokedAt: null }, data: { revokedAt: now } }); const expiresAt = new Date(now.valueOf() + TOKEN_TTL_MS); await tx.workerEnrollmentToken.create({ data: { id: uuidV7(), workerId: id, tokenPrefix: token.slice(0, 12), tokenHash, expiresAt } }); const updated = await tx.worker.update({ where: { id }, data: { version: { increment: 1 } } }); const safe = { workerId: id, version: updated.version }; await tx.idempotencyRecord.create({ data: { id: uuidV7(), scope, key: keyHash, requestHash, responseBody: safe, responseEtag: `"${updated.version}"` } }); await this.event(tx, id, updated.version, 'WORKER_ENROLLMENT_TOKEN_ISSUED'); return { ...safe, secretAvailable: true, token, expiresAt: expiresAt.toISOString() };
    }, { isolationLevel: 'Serializable' });
  }
  drain(id: string, version: number, key: string) { return this.action('WORKER_DRAIN_V1', id, version, key, async (tx, row) => { if (row.desiredStatus === 'REVOKED' || row.observedStatus === 'TERMINATED') throw new WorkerError('WORKER_NOT_DRAINABLE', 'Worker cannot drain from its current state'); const active = await tx.taskLease.count({ where: { workerSession: { workerId: id }, releasedAt: null } }); return tx.worker.update({ where: { id }, data: { desiredStatus: 'DRAINING', observedStatus: active ? 'DRAINING' : 'SAFE_TO_TERMINATE', version: { increment: 1 } } }); }); }
  revoke(id: string, version: number, key: string) { return this.action('WORKER_REVOKE_V1', id, version, key, async (tx) => { const now = new Date(); await tx.workerCredential.updateMany({ where: { workerId: id, revokedAt: null }, data: { revokedAt: now } }); await tx.workerEnrollmentToken.updateMany({ where: { workerId: id, consumedAt: null, revokedAt: null }, data: { revokedAt: now } }); return tx.worker.update({ where: { id }, data: { desiredStatus: 'REVOKED', version: { increment: 1 } } }); }); }
  confirmTermination(id: string, version: number, key: string) { return this.action('WORKER_CONFIRM_TERMINATION_V1', id, version, key, async (tx, row) => { const active = await tx.taskLease.count({ where: { workerSession: { workerId: id }, releasedAt: null } }); if (active || (row.observedStatus !== 'SAFE_TO_TERMINATE' && row.desiredStatus !== 'REVOKED')) throw new WorkerError('WORKER_NOT_SAFE_TO_TERMINATE', 'Worker still has active work'); const now = new Date(); await tx.workerSession.updateMany({ where: { workerId: id, endedAt: null }, data: { endedAt: now, endReason: 'TERMINATED' } }); await tx.workerBillingSession.updateMany({ where: { workerId: id, billingEndedAt: null }, data: { billingEndedAt: now, terminationConfirmedAt: now } }); return tx.worker.update({ where: { id }, data: { observedStatus: 'TERMINATED', version: { increment: 1 } } }); }); }
  async enroll(prefix: string, tokenHash: string, input: EnrollmentInput, credential: string, credentialHash: string) {
    return this.prisma.$transaction(async (tx) => { const token = await tx.workerEnrollmentToken.findFirst({ where: { tokenPrefix: prefix, tokenHash }, include: { worker: { include: { approvedImage: true } } } }); if (!token) throw new WorkerError('ENROLLMENT_TOKEN_INVALID', 'Enrollment credential is invalid'); if (token.revokedAt) throw new WorkerError('ENROLLMENT_TOKEN_INVALID', 'Enrollment credential is invalid'); if (token.consumedAt) throw new WorkerError('ENROLLMENT_TOKEN_CONSUMED', 'Enrollment credential was already consumed'); if (token.expiresAt < new Date()) throw new WorkerError('ENROLLMENT_TOKEN_EXPIRED', 'Enrollment credential has expired'); const worker = token.worker; if (worker.desiredStatus !== 'ACTIVE') throw new WorkerError('WORKER_NOT_ACTIVE', 'Worker is not active'); validateIdentity(worker, input); const active = await tx.workerSession.findFirst({ where: { workerId: worker.id, endedAt: null } }); if (active) throw new WorkerError('WORKER_SESSION_CONFLICT', 'Worker already has an active session'); const billing = await tx.workerBillingSession.findFirst({ where: { workerId: worker.id, billingEndedAt: null } }); if (!billing) throw new WorkerError('WORKER_NOT_ACTIVE', 'Worker billing session is closed'); const now = new Date(); await tx.workerEnrollmentToken.update({ where: { id: token.id }, data: { consumedAt: now } }); await tx.workerCredential.updateMany({ where: { workerId: worker.id, revokedAt: null }, data: { revokedAt: now } }); const savedCredential = await tx.workerCredential.create({ data: { id: uuidV7(), workerId: worker.id, credentialPrefix: credential.slice(0, 12), credentialHash, scopes: ['session', 'heartbeat'] } }); const session = await tx.workerSession.create({ data: { id: uuidV7(), workerId: worker.id, credentialId: savedCredential.id, billingSessionId: billing.id, sessionNonce: input.sessionNonce, imageId: worker.approvedImageId, imageDigest: input.imageDigest, agentVersion: input.agentVersion, contractVersion: input.contractVersion, gpuInventory: input.gpuInventory as Prisma.InputJsonValue, cpuInventory: input.cpuInventory as Prisma.InputJsonValue, capacity: input.capacity as Prisma.InputJsonValue } }); await tx.worker.update({ where: { id: worker.id }, data: { observedStatus: 'READY', lastErrorCode: null, lastErrorDetailSafe: null, version: { increment: 1 } } }); await this.event(tx, worker.id, worker.version + 1, 'WORKER_ENROLLED'); return { credential, session: sessionView(session), heartbeatIntervalSeconds: 15, offlineTimeoutSeconds: 45 }; }, { isolationLevel: 'Serializable' });
  }
  async startSession(prefix: string, credentialHash: string, input: EnrollmentInput) { const auth = await this.credential(prefix, credentialHash); return this.prisma.$transaction(async (tx) => { const worker = await tx.worker.findUnique({ where: { id: auth.workerId }, include: { approvedImage: true } }); if (!worker || worker.desiredStatus !== 'ACTIVE') throw new WorkerError('WORKER_NOT_ACTIVE', 'Worker is not active'); validateIdentity(worker, input); const active = await tx.workerSession.findFirst({ where: { workerId: worker.id, endedAt: null } }); if (active) { const leases = await tx.taskLease.count({ where: { workerSessionId: active.id, releasedAt: null } }); if (leases) throw new WorkerError('WORKER_SESSION_CONFLICT', 'The active session still owns leases'); await tx.workerSession.update({ where: { id: active.id }, data: { endedAt: new Date(), endReason: 'REPLACED' } }); } const billing = await tx.workerBillingSession.findFirstOrThrow({ where: { workerId: worker.id, billingEndedAt: null } }); const session = await tx.workerSession.create({ data: { id: uuidV7(), workerId: worker.id, credentialId: auth.id, billingSessionId: billing.id, sessionNonce: input.sessionNonce, imageId: worker.approvedImageId, imageDigest: input.imageDigest, agentVersion: input.agentVersion, contractVersion: input.contractVersion, gpuInventory: input.gpuInventory as Prisma.InputJsonValue, cpuInventory: input.cpuInventory as Prisma.InputJsonValue, capacity: input.capacity as Prisma.InputJsonValue } }); await tx.worker.update({ where: { id: worker.id }, data: { observedStatus: 'READY', version: { increment: 1 } } }); return { session: sessionView(session), heartbeatIntervalSeconds: 15, offlineTimeoutSeconds: 45 }; }); }
  async heartbeat(prefix: string, credentialHash: string, sessionId: string, input: HeartbeatInput) { const auth = await this.credential(prefix, credentialHash); const current = await this.prisma.workerSession.findUnique({ where: { id: sessionId }, include: { worker: { include: { approvedImage: true } } } }); if (!current || current.workerId !== auth.workerId || current.endedAt || current.worker.desiredStatus === 'REVOKED') throw new WorkerError('WORKER_CREDENTIAL_REVOKED', 'Worker session is unavailable'); if (current.worker.approvedImage.status !== 'ACTIVE' || input.contractVersion !== current.contractVersion || input.agentVersion !== current.agentVersion) { await this.prisma.worker.update({ where: { id: current.workerId }, data: { observedStatus: 'ERROR', lastErrorCode: 'WORKER_VERSION_MISMATCH', lastErrorDetailSafe: 'Worker image or contract version is not approved', version: { increment: 1 } } }); throw new WorkerError('WORKER_VERSION_MISMATCH', 'Worker image or contract version is not approved'); } return this.prisma.$transaction(async (tx) => { const session = await tx.workerSession.findUnique({ where: { id: sessionId }, include: { worker: true } }); if (!session || session.endedAt) throw new WorkerError('WORKER_CREDENTIAL_REVOKED', 'Worker session is unavailable'); const sequence = BigInt(input.sequence); if (sequence > session.lastHeartbeatSequence) { const active = await tx.taskLease.count({ where: { workerSessionId: session.id, releasedAt: null } }); const status = session.worker.desiredStatus === 'DRAINING' ? (active ? 'DRAINING' : 'SAFE_TO_TERMINATE') : active || input.currentTaskCount ? 'BUSY' : 'READY'; await tx.workerSession.update({ where: { id: session.id }, data: { capacity: input.capacity as Prisma.InputJsonValue, telemetrySafe: input.telemetry as Prisma.InputJsonValue, currentTaskCount: input.currentTaskCount, lastHeartbeatSequence: sequence, lastHeartbeatAt: new Date(), ...(session.worker.desiredStatus === 'DRAINING' && !session.drainingAt ? { drainingAt: new Date() } : {}) } }); await tx.workerCredential.update({ where: { id: auth.id }, data: { lastUsedAt: new Date() } }); await tx.worker.update({ where: { id: session.workerId }, data: { observedStatus: status, version: { increment: 1 } } }); } return { acceptedSequence: input.sequence, workerId: session.workerId, sessionId: session.id }; }); }
  events(): Observable<{ id: string; type: string; data: unknown }> { const connectedAt = new Date(); return new Observable((subscriber) => { let timer: ReturnType<typeof setTimeout> | undefined; let closed = false; let last = connectedAt; const poll = async () => { try { const rows = await this.prisma.outboxMessage.findMany({ where: { eventType: 'worker.invalidate', occurredAt: { gt: last } }, orderBy: { occurredAt: 'asc' }, take: 100 }); for (const row of rows) { last = row.occurredAt; subscriber.next({ id: row.id, type: row.eventType, data: row.payloadSafe }); } if (!closed) timer = setTimeout(poll, 1_000); } catch (error) { subscriber.error(error); } }; void poll(); return () => { closed = true; if (timer) clearTimeout(timer); }; }); }
  private action(scope: string, id: string, version: number, key: string, action: (tx: Prisma.TransactionClient, row: Prisma.WorkerGetPayload<object>) => Promise<unknown>) { return this.mutate(scope, key, hash({ id, version }), async (tx) => { const row = await tx.worker.findUnique({ where: { id } }); if (!row) missing(); if (row.version !== version) conflict(); await action(tx, row); const result = view(await this.rowWith(tx, id)); await this.event(tx, id, result.version, scope); return result; }); }
  private async credential(prefix: string, credentialHash: string) { const row = await this.prisma.workerCredential.findFirst({ where: { credentialPrefix: prefix, credentialHash, revokedAt: null } }); if (!row || row.expiresAt && row.expiresAt < new Date()) throw new WorkerError('WORKER_CREDENTIAL_REVOKED', 'Worker credential is invalid'); return row; }
  private mutate<T>(scope: string, key: string, requestHash: string, action: (tx: Prisma.TransactionClient) => Promise<T>, persist = true) { const keyHash = hash(key); return this.prisma.$transaction(async (tx) => { const old = await tx.idempotencyRecord.findUnique({ where: { scope_key: { scope, key: keyHash } } }); if (old) { if (old.requestHash !== requestHash) reused(); return old.responseBody as unknown as T; } const result = await action(tx); if (persist) await tx.idempotencyRecord.create({ data: { id: uuidV7(), scope, key: keyHash, requestHash, responseBody: result as unknown as Prisma.InputJsonValue, responseEtag: '' } }); return result; }, { isolationLevel: 'Serializable' }); }
  private async row(id: string) { const row = await this.prisma.worker.findUnique({ where: { id }, include: workerInclude }); if (!row) missing(); return row; }
  private async rowWith(tx: Prisma.TransactionClient, id: string) { const row = await tx.worker.findUnique({ where: { id }, include: workerInclude }); if (!row) missing(); return row; }
  private refreshOffline() { return this.prisma.worker.updateMany({ where: { observedStatus: { in: ['READY', 'BUSY', 'DRAINING'] }, sessions: { some: { endedAt: null, lastHeartbeatAt: { lt: new Date(Date.now() - OFFLINE_MS) } } } }, data: { observedStatus: 'OFFLINE', version: { increment: 1 } } }); }
  private async event(tx: Prisma.TransactionClient, id: string, version: number, reason: string) { await tx.outboxMessage.create({ data: { id: uuidV7(), aggregateType: 'WORKER', aggregateId: id, eventType: 'worker.invalidate', payloadSafe: { workerId: id, workerVersion: version, reason } } }); }
}
function view(row: WorkerRow) { const session = row.sessions[0]; const billing = row.billingSessions[0]; const elapsed = billing ? Math.max(0, ((billing.billingEndedAt ?? new Date()).valueOf() - billing.billingStartedAt.valueOf()) / 3_600_000) : 0; const estimated = billing ? Number(billing.hourlyRateCp) * elapsed : null; return { id: row.id, displayName: row.displayName, role: row.role, provider: row.provider, providerInstanceId: row.providerInstanceId, mode: row.mode, desiredStatus: row.desiredStatus, observedStatus: row.observedStatus, expectedGpuModel: row.expectedGpuModel, expectedVramMb: row.expectedVramMb, approvedImage: imageView(row.approvedImage), currentSession: session ? sessionView(session) : null, activeLeaseCount: session?.taskLeases.length ?? 0, safeToTerminate: row.observedStatus === 'SAFE_TO_TERMINATE', billing: billing ? { id: billing.id, hourlyRateCp: billing.hourlyRateCp.toString(), paidVndPerCp: billing.paidVndPerCp?.toString() ?? null, billingStartedAt: billing.billingStartedAt.toISOString(), billingEndedAt: billing.billingEndedAt?.toISOString() ?? null, estimatedCostCp: estimated?.toFixed(6) ?? null } : null, lastError: row.lastErrorCode ? { code: row.lastErrorCode, detail: row.lastErrorDetailSafe } : null, version: row.version, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }; }
function imageView(row: { id: string; role: WorkerRole; semanticVersion: string; imageDigest: string; registryRef: string; contractVersion: number; status: string; approvedAt: Date; revokedAt: Date | null; version: number }) { return { id: row.id, role: row.role, semanticVersion: row.semanticVersion, imageDigest: row.imageDigest, registryRef: row.registryRef, contractVersion: row.contractVersion, status: row.status, approvedAt: row.approvedAt.toISOString(), revokedAt: row.revokedAt?.toISOString() ?? null, version: row.version }; }
function sessionView(row: { id: string; sessionNonce: string; imageDigest: string; agentVersion: string; contractVersion: number; gpuInventory: unknown; cpuInventory: unknown; capacity: unknown; telemetrySafe: unknown; currentTaskCount: number; lastHeartbeatSequence: bigint; startedAt: Date; lastHeartbeatAt: Date; drainingAt: Date | null; endedAt: Date | null; endReason: string | null }) { return { id: row.id, sessionNonce: row.sessionNonce, imageDigest: row.imageDigest, agentVersion: row.agentVersion, contractVersion: row.contractVersion, gpuInventory: row.gpuInventory, cpuInventory: row.cpuInventory, capacity: row.capacity, telemetry: row.telemetrySafe, currentTaskCount: row.currentTaskCount, lastHeartbeatSequence: row.lastHeartbeatSequence.toString(), startedAt: row.startedAt.toISOString(), lastHeartbeatAt: row.lastHeartbeatAt.toISOString(), drainingAt: row.drainingAt?.toISOString() ?? null, endedAt: row.endedAt?.toISOString() ?? null, endReason: row.endReason }; }
function validateIdentity(worker: { role: WorkerRole; expectedGpuModel: string | null; expectedVramMb: number | null; approvedImage: { imageDigest: string; contractVersion: number; status: string } }, input: EnrollmentInput) { if (worker.approvedImage.status !== 'ACTIVE' || worker.role !== input.role || worker.approvedImage.imageDigest !== input.imageDigest || worker.approvedImage.contractVersion !== input.contractVersion) throw new WorkerError('WORKER_VERSION_MISMATCH', 'Worker image, role or contract version is not approved'); const inventory = input.gpuInventory as Array<{ model?: string; vramMb?: number }>; if (worker.expectedGpuModel && !inventory.some((gpu) => gpu.model === worker.expectedGpuModel) || worker.expectedVramMb && !inventory.some((gpu) => (gpu.vramMb ?? 0) >= worker.expectedVramMb!)) throw new WorkerError('WORKER_HARDWARE_MISMATCH', 'Worker hardware does not meet the registered minimum'); }
function encodeCursor(createdAt: Date, id: string) { return Buffer.from(JSON.stringify({ createdAt: createdAt.toISOString(), id })).toString('base64url'); }
function decodeCursor(value?: string): { createdAt: Date; id: string } | null { if (!value) return null; try { const parsed = JSON.parse(Buffer.from(value, 'base64url').toString()) as { createdAt: string; id: string }; return { createdAt: new Date(parsed.createdAt), id: parsed.id }; } catch { throw new WorkerError('WORKER_VALIDATION_FAILED', 'Worker cursor is invalid'); } }
function hash(value: unknown) { return createHash('sha256').update(typeof value === 'string' ? value : JSON.stringify(value)).digest('hex'); }
function missing(): never { throw new WorkerError('WORKER_NOT_FOUND', 'Worker was not found'); }
function conflict(): never { throw new WorkerError('VERSION_CONFLICT', 'Worker version is stale'); }
function reused(): never { throw new WorkerError('IDEMPOTENCY_KEY_REUSED', 'Idempotency-Key was already used with another request'); }
