import { cancelDiscoveryRun, createClient, createDiscoveryRun, createSourceAccount, createWatchlist, deleteWatchlist, getDiscoveryRun, importSourceCredential, listDiscoveryCategories, listDiscoveryItems, listSourceAccounts, listWatchlists, runWatchlist, updateWatchlist, type Availability, type CreateDiscoveryRun, type DiscoveryItem, type DiscoveryRun, type SourceAccount, type SourceContentType, type UpdateWatchlist, type Watchlist } from '@reup-dubbing-studio/api-client';
import { z } from 'zod';
import { getSafeRequestId } from '@/shared/api/problem-details';
import { readRuntimeConfig } from '@/shared/config/runtime-config';

const uuid = z.string().uuid(); const meta = z.object({ requestId: uuid });
const credential = z.object({ kind: z.literal('NETSCAPE_COOKIE'), importedAt: z.string().datetime(), expiresAt: z.string().datetime().nullable() });
const account = z.object({ id: uuid, platform: z.enum(['DOUYIN', 'BILIBILI', 'YOUTUBE']), displayName: z.string(), status: z.enum(['ACTIVE', 'EXPIRED', 'CAPTCHA_REQUIRED', 'INVALID', 'REVOKED']), credential: credential.nullable(), lastValidatedAt: z.string().datetime().nullable(), lastSuccessAt: z.string().datetime().nullable(), consecutiveFailures: z.number().int(), cooldownUntil: z.string().datetime().nullable(), version: z.number().int(), createdAt: z.string().datetime(), updatedAt: z.string().datetime() });
const category = z.object({ id: uuid, platform: z.enum(['DOUYIN', 'BILIBILI', 'YOUTUBE']), externalKey: z.string(), slug: z.string().nullable(), label: z.string(), kind: z.string(), parentId: uuid.nullable() });
const run = z.object({ id: uuid, sourceAccountId: uuid, mode: z.enum(['JINGXUAN', 'CATEGORY', 'COURSE', 'CREATOR', 'MIX', 'SEARCH_VIDEO', 'SEARCH_USER', 'VIDEO_URL', 'WATCHLIST']), status: z.enum(['QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED']), input: z.string().nullable(), query: z.string().nullable(), categoryId: uuid.nullable(), watchlistId: uuid.nullable(), requestedLimit: z.number().int().nullable(), pageCount: z.number().int(), itemCount: z.number().int(), skippedCounts: z.record(z.string(), z.number().int()), errorCode: z.string().nullable(), errorDetail: z.string().nullable(), version: z.number().int(), startedAt: z.string().datetime().nullable(), finishedAt: z.string().datetime().nullable(), createdAt: z.string().datetime(), updatedAt: z.string().datetime() });
const creator = z.object({ id: uuid, externalId: z.string(), nickname: z.string().nullable(), profileUrl: z.string().url().nullable() });
const metrics = z.object({ capturedAt: z.string().datetime(), playCount: z.string().nullable(), diggCount: z.string().nullable(), commentCount: z.string().nullable(), collectCount: z.string().nullable(), shareCount: z.string().nullable() });
const item = z.object({ id: uuid, runId: uuid, rank: z.number().int(), discoveredAt: z.string().datetime(), sourceContent: z.object({ id: uuid, platform: z.enum(['DOUYIN', 'BILIBILI', 'YOUTUBE']), externalId: z.string(), contentType: z.enum(['VIDEO', 'LONG_VIDEO', 'NOTE', 'SLIDES', 'ARTICLE', 'LIVE', 'UNKNOWN']), title: z.string().nullable(), description: z.string().nullable(), canonicalUrl: z.string().url().nullable(), publishedAt: z.string().datetime().nullable(), durationMs: z.number().int().nullable(), width: z.number().int().nullable(), height: z.number().int().nullable(), availability: z.enum(['AVAILABLE', 'PRIVATE', 'REMOVED', 'REGION_BLOCKED', 'UNKNOWN']), ingestEligible: z.boolean(), firstSeenAt: z.string().datetime(), lastSeenAt: z.string().datetime(), creator: creator.nullable(), categories: z.array(category), cover: z.object({ url: z.string().url(), requiresRefresh: z.boolean() }).nullable(), metrics: metrics.nullable() }) });
const watchlist = z.object({ id: uuid, sourceAccountId: uuid, mode: z.literal('CREATOR'), resolvedInput: z.record(z.string(), z.unknown()), displayName: z.string(), status: z.enum(['ACTIVE', 'PAUSED', 'CREDENTIAL_REQUIRED', 'FAILED']), scheduleIntervalMin: z.number().int(), nextRunAt: z.string().datetime(), lastRunAt: z.string().datetime().nullable(), lastSuccessAt: z.string().datetime().nullable(), consecutiveFailures: z.number().int(), version: z.number().int(), createdAt: z.string().datetime(), updatedAt: z.string().datetime() });
const envelope = <T extends z.ZodTypeAny>(schema: T) => z.object({ data: schema, meta });

export type DiscoveryFilters = { runId?: string; categoryId?: string; contentType?: SourceContentType; availability?: Availability; ingestEligible?: boolean; cursor?: string; limit?: number };
export class DiscoveryApiError extends Error { override readonly name = 'DiscoveryApiError'; constructor(message: string, readonly code?: string, readonly requestId?: string) { super(message); } }
function apiClient() { return createClient({ baseUrl: readRuntimeConfig().controlPlaneUrl }); }
export async function fetchSourceAccounts(signal?: AbortSignal) { return parse(await listSourceAccounts({ client: apiClient(), query: { platform: 'DOUYIN' }, signal: requestSignal(signal) }), envelope(z.object({ items: z.array(account) })), 'Không thể tải tài khoản nguồn.').data.items as SourceAccount[]; }
export async function addSourceAccount(displayName: string) { return parse(await createSourceAccount({ client: apiClient(), headers: { 'Idempotency-Key': crypto.randomUUID() }, body: { platform: 'DOUYIN', displayName } }), envelope(account), 'Không thể tạo tài khoản nguồn.').data as SourceAccount; }
export async function saveSourceCookie(id: string, netscapeCookie: string) { return parse(await importSourceCredential({ client: apiClient(), path: { sourceAccountId: id }, body: { netscapeCookie } }), envelope(account), 'Không thể nhập cookie.').data as SourceAccount; }
export async function fetchCategories(signal?: AbortSignal) { return parse(await listDiscoveryCategories({ client: apiClient(), query: { platform: 'DOUYIN' }, signal: requestSignal(signal) }), envelope(z.object({ items: z.array(category) })), 'Không thể tải category.').data.items; }
export async function startDiscovery(body: CreateDiscoveryRun) { return parse(await createDiscoveryRun({ client: apiClient(), headers: { 'Idempotency-Key': crypto.randomUUID() }, body }), envelope(run), 'Không thể bắt đầu quét.').data as DiscoveryRun; }
export async function fetchDiscoveryRun(id: string, signal?: AbortSignal) { return parse(await getDiscoveryRun({ client: apiClient(), path: { discoveryRunId: id }, signal: requestSignal(signal) }), envelope(run), 'Không thể đọc trạng thái quét.').data as DiscoveryRun; }
export async function stopDiscovery(id: string) { return parse(await cancelDiscoveryRun({ client: apiClient(), path: { discoveryRunId: id } }), envelope(run), 'Không thể hủy quét.').data as DiscoveryRun; }
export async function fetchDiscoveryItems(filters: DiscoveryFilters, signal?: AbortSignal) { return parse(await listDiscoveryItems({ client: apiClient(), query: filters, signal: requestSignal(signal) }), envelope(z.object({ items: z.array(item), nextCursor: z.string().nullable() })), 'Không thể tải kết quả Discovery.').data as { items: DiscoveryItem[]; nextCursor: string | null }; }
export async function fetchWatchlists(signal?: AbortSignal) { return parse(await listWatchlists({ client: apiClient(), signal: requestSignal(signal) }), envelope(z.object({ items: z.array(watchlist) })), 'Không thể tải watchlist.').data.items as Watchlist[]; }
export async function addWatchlist(input: { sourceAccountId: string; input: string; displayName: string; scheduleIntervalMin: number }) { return parse(await createWatchlist({ client: apiClient(), headers: { 'Idempotency-Key': crypto.randomUUID() }, body: { ...input, mode: 'CREATOR' } }), envelope(watchlist), 'Không thể tạo watchlist.').data as Watchlist; }
export async function saveWatchlist(id: string, version: number, body: UpdateWatchlist) { return parse(await updateWatchlist({ client: apiClient(), path: { watchlistId: id }, headers: { 'If-Match': `"${version}"` }, body }), envelope(watchlist), 'Không thể cập nhật watchlist.').data as Watchlist; }
export async function removeWatchlist(id: string, version: number) { const result = await deleteWatchlist({ client: apiClient(), path: { watchlistId: id }, headers: { 'If-Match': `"${version}"` } }); if (result.error) throw apiError(result.error, result.response, 'Không thể xóa watchlist.'); }
export async function scanWatchlist(id: string) { return parse(await runWatchlist({ client: apiClient(), path: { watchlistId: id }, headers: { 'Idempotency-Key': crypto.randomUUID() } }), envelope(run), 'Không thể quét watchlist.').data as DiscoveryRun; }
type ApiResult = { data?: unknown; error?: unknown; response: Response };
function parse<T>(result: ApiResult, schema: z.ZodType<T>, fallback: string): T { if (result.error) throw apiError(result.error, result.response, fallback); const parsed = schema.safeParse(result.data); if (!parsed.success) throw new DiscoveryApiError('Control Plane trả về dữ liệu Discovery không hợp lệ.'); return parsed.data; }
function apiError(value: unknown, response: Response, fallback: string) { const problem = value as { code?: unknown; detail?: unknown }; return new DiscoveryApiError(typeof problem.detail === 'string' ? problem.detail : fallback, typeof problem.code === 'string' ? problem.code : undefined, getSafeRequestId(value, response.headers.get('X-Request-Id'))); }
function requestSignal(signal?: AbortSignal) { if (!signal) return null; try { new Request('about:blank', { signal }); return signal; } catch { return null; } }
